updating dockerfiles set
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

diff --git a/data/b/blacktop/kibana-plugin-builder/Dockerfile b/data/b/blacktop/kibana-plugin-builder/Dockerfile
--- a/data/b/blacktop/kibana-plugin-builder/Dockerfile
+++ b/data/b/blacktop/kibana-plugin-builder/Dockerfile
@@ -1,78 +1,97 @@
-FROM alpine:3.7  
-  
-LABEL maintainer "https://github.com/blacktop"  
-LABEL credit "hhttps://github.com/nodejs/docker-node"  
-  
-ENV NPM_CONFIG_LOGLEVEL info  
-ARG NODE_VERSION=6.12.2  
-  
-RUN addgroup -g 1000 node \  
-&& adduser -u 1000 -G node -s /bin/sh -D node \  
-&& apk add --no-cache \  
-libstdc++ \  
-&& apk add --no-cache --virtual .build-deps \  
-binutils-gold \  
-curl \  
-g++ \  
-gcc \  
-gnupg \  
-libgcc \  
-linux-headers \  
-make \  
-python \  
-# gpg keys listed at https://github.com/nodejs/node#release-team  
-&& for key in \  
-9554F04D7259F04124DE6B476D5A82AC7E37093B \  
-94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \  
-FD3A5288F042B6850C66B31F09FE44734EB7990E \  
-71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \  
-DD8F2338BAE7501E3DD5AC78C273792F7D83545D \  
-B9AE9905FFD7803F25714661B63B535A4C206CA9 \  
-C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \  
-56730D5401028683275BD23C23EFEFE93C4CFFFE \  
-; do \  
-gpg --keyserver pgp.mit.edu --recv-keys "$key" || \  
-gpg --keyserver keyserver.pgp.com --recv-keys "$key" || \  
-gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ; \  
-done \  
-&& curl -SLO
-"https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION.tar.xz" \  
-&& curl -SLO --compressed
-"https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \  
-&& gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \  
-&& grep " node-v$NODE_VERSION.tar.xz\$" SHASUMS256.txt | sha256sum -c - \  
-&& tar -xf "node-v$NODE_VERSION.tar.xz" \  
-&& cd "node-v$NODE_VERSION" \  
-&& ./configure \  
-&& make -j$(getconf _NPROCESSORS_ONLN) \  
-&& make install \  
-&& apk del .build-deps \  
-&& cd .. \  
-&& rm -Rf "node-v$NODE_VERSION" \  
-&& rm "node-v$NODE_VERSION.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt  
-  
-ENV YARN_VERSION 0.24.6  
-  
-RUN apk add --no-cache --virtual .build-deps-yarn curl gnupg tar \  
-&& for key in \  
-6A010C5166006599AA17F08146C2130DFD2497F5 \  
-; do \  
-gpg --keyserver pgp.mit.edu --recv-keys "$key" || \  
-gpg --keyserver keyserver.pgp.com --recv-keys "$key" || \  
-gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ; \  
-done \  
-&& curl -fSLO --compressed
-"https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \  
-&& curl -fSLO --compressed
-"https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc" \  
-&& gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc
-yarn-v$YARN_VERSION.tar.gz \  
-&& mkdir -p /opt/yarn \  
-&& tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/yarn --strip-components=1 \  
-&& ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \  
-&& ln -s /opt/yarn/bin/yarn /usr/local/bin/yarnpkg \  
-&& rm yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \  
-&& apk del .build-deps-yarn  
-  
-CMD [ "node" ]  
+FROM node:10.15.2-stretch-slim
 
+LABEL maintainer "https://github.com/blacktop"
+
+RUN apt-get update && apt-get install -y --no-install-recommends \
+	git \
+	bzip2 \
+	unzip \
+	xz-utils \
+	&& rm -rf /var/lib/apt/lists/*
+
+RUN echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/stretch-backports.list
+
+# Default to UTF-8 file.encoding
+ENV LANG C.UTF-8
+
+# add a simple script that can auto-detect the appropriate JAVA_HOME value
+# based on whether the JDK or only the JRE is installed
+RUN { \
+	echo '#!/bin/sh'; \
+	echo 'set -e'; \
+	echo; \
+	echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
+	} > /usr/local/bin/docker-java-home \
+	&& chmod +x /usr/local/bin/docker-java-home
+
+# do some fancy footwork to create a JAVA_HOME that's cross-architecture-safe
+RUN ln -svT "/usr/lib/jvm/java-11-openjdk-$(dpkg --print-architecture)" /docker-java-home
+ENV JAVA_HOME /docker-java-home
+
+ENV JAVA_VERSION 11.0.3
+ENV JAVA_DEBIAN_VERSION 11.0.3+1-1~bpo9+1
+
+RUN set -ex; \
+	\
+	# deal with slim variants not having man page directories (which causes "update-alternatives" to fail)
+	if [ ! -d /usr/share/man/man1 ]; then \
+	mkdir -p /usr/share/man/man1; \
+	fi; \
+	\
+	# ca-certificates-java does not work on src:openjdk-11 with no-install-recommends: (https://bugs.debian.org/914860, https://bugs.debian.org/775775)
+	# /var/lib/dpkg/info/ca-certificates-java.postinst: line 56: java: command not found
+	ln -svT /docker-java-home/bin/java /usr/local/bin/java; \
+	\
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+	openjdk-11-jre="$JAVA_DEBIAN_VERSION" \
+	; \
+	rm -rf /var/lib/apt/lists/*; \
+	\
+	rm -v /usr/local/bin/java; \
+	\
+	# ca-certificates-java does not work on src:openjdk-11: (https://bugs.debian.org/914424, https://bugs.debian.org/894979, https://salsa.debian.org/java-team/ca-certificates-java/commit/813b8c4973e6c4bb273d5d02f8d4e0aa0b226c50#d4b95d176f05e34cd0b718357c532dc5a6d66cd7_54_56)
+	keytool -importkeystore -srckeystore /etc/ssl/certs/java/cacerts -destkeystore /etc/ssl/certs/java/cacerts.jks -deststoretype JKS -srcstorepass changeit -deststorepass changeit -noprompt; \
+	mv /etc/ssl/certs/java/cacerts.jks /etc/ssl/certs/java/cacerts; \
+	/var/lib/dpkg/info/ca-certificates-java.postinst configure; \
+	\
+	# verify that "docker-java-home" returns what we expect
+	[ "$(readlink -f "$JAVA_HOME")" = "$(docker-java-home)" ]; \
+	\
+	# update-alternatives so that future installs of other OpenJDK versions don't change /usr/bin/java
+	update-alternatives --get-selections | awk -v home="$(readlink -f "$JAVA_HOME")" 'index($3, home) == 1 { $2 = "manual"; print | "update-alternatives --set-selections" }'; \
+	# ... and verify that it actually worked for one of the alternatives we care about
+	update-alternatives --query java | grep -q 'Status: manual'
+
+ENV PATH=${PATH}:${JAVA_HOME}/bin:/plugin/kibana/bin:${PATH}
+
+ARG VERSION=7.0.0
+
+COPY node-prune.sh /usr/bin/node-prune
+RUN echo "===> Installing elasticdump" \
+	&& set -ex \
+	&& yarn global add elasticdump \
+	&& cd /usr/local/lib/ && node-prune || true
+
+WORKDIR /plugin
+
+RUN echo "===> Cloning Kibana v$VERSION" \
+	&& git clone --depth 1 -b v${VERSION} https://github.com/elastic/kibana.git
+
+WORKDIR /plugin/kibana
+
+# Install kibana node_modules
+RUN set -ex \
+	&& yarn kbn bootstrap \
+	&& cd /usr/local/lib \
+	&& node-prune || true \
+	&& chown -R node:node /plugin
+
+COPY entrypoint.sh /entrypoint.sh
+RUN chown node:node /entrypoint.sh
+
+USER node
+
+EXPOSE 5601 9200
+
+ENTRYPOINT ["/entrypoint.sh"]
diff --git a/data/c/crunchgeek/php-fpm/Dockerfile b/data/c/crunchgeek/php-fpm/Dockerfile
--- a/data/c/crunchgeek/php-fpm/Dockerfile
+++ b/data/c/crunchgeek/php-fpm/Dockerfile
@@ -1,322 +1,153 @@
-FROM php:7.1-fpm  
-  
-MAINTAINER Mark Hilton <nerd305@gmail.com>  
-  
-RUN apt-get update && \  
-apt-get install -y --no-install-recommends \  
-git \  
-libmemcached-dev \  
-libz-dev \  
-libpq-dev \  
-libjpeg-dev \  
-libpng12-dev \  
-libfreetype6-dev \  
-libssl-dev \  
-libmcrypt-dev  
-  
-RUN docker-php-ext-install mcrypt  
-RUN docker-php-ext-install mysqli pdo pdo_mysql  
-  
-# install the PHP gd library  
-RUN docker-php-ext-configure gd \  
-\--enable-gd-native-ttf \  
-\--with-jpeg-dir=/usr/lib \  
-\--with-freetype-dir=/usr/include/freetype2 && \  
-docker-php-ext-install gd  
-  
-# install the soap extension  
-RUN apt-get update -yqq && \  
-apt-get -y install libxml2-dev && \  
-docker-php-ext-install soap  
-  
-# install Php Redis Extension  
-RUN pecl install -o -f redis \  
-&& rm -rf /tmp/pear \  
-&& docker-php-ext-enable redis  
-  
-# install the mongodb extension  
-RUN pecl install mongodb && \  
-docker-php-ext-enable mongodb  
-  
-# install bcmath, mbstring and zip extensions  
-RUN docker-php-ext-install bcmath && \  
-docker-php-ext-install mbstring && \  
-docker-php-ext-install zip  
-  
-# enable Exif PHP extentions requirements  
-RUN docker-php-ext-install exif  
-  
-# tokenizer Modifications:  
-RUN docker-php-ext-install tokenizer  
-  
-# install intl and requirements  
-RUN apt-get update -yqq && \  
-apt-get install -y zlib1g-dev libicu-dev g++ && \  
-docker-php-ext-configure intl && \  
-docker-php-ext-install intl  
-  
-# install the ghostscript extension for PDF editing  
-RUN apt-get update -yqq \  
-&& apt-get install -y \  
-poppler-utils \  
-ghostscript  
-  
-# LDAP:  
-RUN apt-get update -yqq && \  
-apt-get install -y libldap2-dev && \  
-docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \  
-docker-php-ext-install ldap  
-  
-RUN yes "" | pecl install msgpack-beta \  
-&& echo "extension=msgpack.so" > /usr/local/etc/php/conf.d/ext-msgpack.ini  
-  
-# compile igbinary extension  
-RUN cd /tmp/ && git clone https://github.com/igbinary/igbinary "php-igbinary"
-&& \  
-cd php-igbinary && \  
-phpize && \  
-./configure && \  
-make && \  
-make install && \  
-make clean && \  
-docker-php-ext-enable igbinary  
-  
-# curl extension  
-RUN apt-get install -y curl libcurl4-openssl-dev --no-install-recommends && \  
-docker-php-ext-install curl  
-  
-# data structures extension  
-RUN pecl install ds && \  
-docker-php-ext-enable ds  
-  
-# imagick  
-RUN apt-get update && apt-get install -y libmagickwand-6.q16-dev --no-install-
-recommends && \  
-ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/MagickWand-config
-/usr/bin && \  
-pecl install imagick && \  
-echo "extension=imagick.so" > /usr/local/etc/php/conf.d/ext-imagick.ini  
-  
-# ssh2 module  
-RUN apt-get install -y libssh2-1-dev && \  
-pecl install ssh2-1.0 && \  
-docker-php-ext-enable ssh2  
-  
-# php-module: curl dom bz2 gd json mysqli pcntl pdo pdo_mysql phar posix  
-RUN apt-get install -y libxml2-dev libbz2-dev re2c libpng++-dev \  
-libpng3 libjpeg-dev libvpx-dev zlib1g-dev libgd-dev \  
-libtidy-dev libxslt1-dev libmagic-dev libexif-dev file \  
-sqlite3 libsqlite3-dev libxslt-dev  
-  
-RUN export CFLAGS="-I/usr/src/php" && \  
-docker-php-ext-install xmlreader xmlwriter  
-  
-RUN docker-php-ext-configure json && \  
-docker-php-ext-configure session && \  
-docker-php-ext-configure ctype && \  
-docker-php-ext-configure tokenizer && \  
-docker-php-ext-configure simplexml && \  
-docker-php-ext-configure dom && \  
-docker-php-ext-configure mbstring && \  
-docker-php-ext-configure zip && \  
-docker-php-ext-configure pdo && \  
-docker-php-ext-configure pdo_sqlite && \  
-docker-php-ext-configure pdo_mysql && \  
-docker-php-ext-configure mysqli && \  
-docker-php-ext-configure iconv && \  
-docker-php-ext-configure xml && \  
-docker-php-ext-configure phar  
-  
-RUN docker-php-ext-install \  
-dom \  
-bz2 \  
-json \  
-pcntl \  
-phar \  
-posix \  
-simplexml \  
-soap \  
-tidy \  
-xml \  
-xmlrpc \  
-xsl \  
-calendar \  
-ctype \  
-fileinfo \  
-ftp \  
-sysvmsg \  
-sysvsem \  
-sysvshm  
-  
-# install the php memcache & memcached extension  
-RUN set -x \  
-&& apt-get update && apt-get install -y --no-install-recommends unzip libssl-
-dev libpcre3 libpcre3-dev \  
-&& cd /tmp \  
-&& curl -sSL -o php7.zip https://github.com/websupport-sk/pecl-
-memcache/archive/php7.zip \  
-&& unzip php7 \  
-&& cd pecl-memcache-php7 \  
-&& /usr/local/bin/phpize \  
-&& ./configure --with-php-config=/usr/local/bin/php-config \  
-&& make \  
-&& make install \  
-&& echo "extension=memcache.so" > /usr/local/etc/php/conf.d/ext-memcache.ini \  
-&& rm -rf /tmp/pecl-memcache-php7 php7.zip  
-  
-RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-
-dev/php-memcached/archive/php7.tar.gz" \  
-&& mkdir -p memcached \  
-&& tar -C memcached -zxvf /tmp/memcached.tar.gz --strip 1 \  
-&& ( \  
-cd memcached \  
-&& phpize \  
-&& ./configure \  
-&& make -j$(nproc) \  
-&& make install \  
-) \  
-&& rm -r memcached \  
-&& rm /tmp/memcached.tar.gz \  
-&& docker-php-ext-enable memcached  
-  
-# mhash  
-RUN apt-get install -y libmhash2 libmhash-dev libc-client-dev libkrb5-dev  
-  
-RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \  
-&& docker-php-ext-install imap  
-  
-RUN docker-php-ext-configure hash \--with-mhash && \  
-docker-php-ext-install hash  
-  
-# Opcache  
-RUN docker-php-ext-install opcache  
-  
-# install APCu  
-RUN pecl install apcu-5.1.8 && \  
-pecl install apcu_bc-1.0.3 && \  
-docker-php-ext-enable apcu --ini-name 10-docker-php-ext-apcu.ini && \  
-docker-php-ext-enable apc --ini-name 20-docker-php-ext-apc.ini  
-  
-# install MSSQL support  
-# install ODBC driver  
-RUN apt-get update -y && apt-get install -y apt-transport-https locales  
-RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&
-\  
-curl https://packages.microsoft.com/config/debian/8/prod.list >
-/etc/apt/sources.list.d/mssql-release.list && \  
-export DEBIAN_FRONTEND=noninteractive && apt-get update -y && \  
-ACCEPT_EULA=Y apt-get install -y msodbcsql unixodbc-dev  
-RUN set -xe \  
-&& pecl install pdo_sqlsrv \  
-&& docker-php-ext-enable pdo_sqlsrv \  
-&& apt-get purge -y unixodbc-dev && apt-get autoremove -y && apt-get clean  
-  
-# set locale to utf-8  
-RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \  
-locale-gen  
-ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'  
-# geoip  
-RUN runtimeRequirements="libgeoip-dev" \  
-&& apt-get update && apt-get install -y ${runtimeRequirements} \  
-&& pecl install geoip-1.1.1 \  
-&& printf "extension=geoip.so\n[geoip]\ngeoip.custom_directory =
-/usr/share/GeoIP/\n" > /usr/local/etc/php/conf.d/ext-geoip.ini  
-  
-RUN mkdir -p /usr/share/GeoIP && cd /usr/share/GeoIP/ && \  
-rm -f GeoIP.dat GeoIPv6.dat && \  
-curl -L -O
-http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz && \  
-curl -L -O
-http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
-&& \  
-gzip -d * && \  
-mv GeoLiteCity.dat GeoIPCity.dat  
-  
-#  
-#--------------------------------------------------------------------------  
-# Final Touches  
-#--------------------------------------------------------------------------  
-#  
-# install helpful libs  
-RUN apt-get -y install libfcgi0ldbl jq nano supervisor mysql-client cron
-redis-tools  
-  
-# crontab fix: https://stackoverflow.com/questions/43323754/cannot-make-
-remove-an-entry-for-the-specified-session-cron  
-RUN sed -i '/session required pam_loginuid.so/c\\#session required
-pam_loginuid.so' /etc/pam.d/cron  
-  
-# composer  
-RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar
-/usr/local/bin/composer && chmod +x /usr/local/bin/composer  
-  
-# laravel installer & npm  
-RUN cd ~/ && composer global require laravel/installer  
-RUN curl -sL https://deb.nodesource.com/setup_9.x | bash - && apt-get install
--y nodejs  
-RUN npm i -g npm  
-  
-ENV PATH="$PATH:/root/.composer/vendor/bin"  
-# install modman  
-RUN curl -s -L https://raw.github.com/colinmollenhour/modman/master/modman-
-installer | bash && \  
-mv ~/bin/modman /usr/sbin/  
-  
-# install NewRelic agent  
-RUN echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee
-/etc/apt/sources.list.d/newrelic.list && \  
-curl https://download.newrelic.com/548C16BF.gpg | apt-key add - && \  
-apt-get -y update && \  
-DEBIAN_FRONTEND=noninteractive apt-get -y install newrelic-php5 newrelic-
-sysmond && \  
-export NR_INSTALL_SILENT=1 && newrelic-install install  
-  
-# install blackfire.io profiler  
-RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \  
-&& curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s
-https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \  
-&& tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \  
-&& mv /tmp/blackfire-*.so $(php -r "echo
-ini_get('extension_dir');")/blackfire.so \  
-&& printf
-"extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" >
-$PHP_INI_DIR/conf.d/blackfire.ini  
-  
-# install SendGrid  
-RUN echo "postfix postfix/mailname string localhost" | debconf-set-selections
-&& \  
-echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-
-selections && \  
-DEBIAN_FRONTEND=noninteractive apt-get install postfix libsasl2-modules -y  
-  
-# install shared PHP code  
-RUN git clone https://github.com/nrk/predis.git /usr/local/lib/php/predis && \  
-git clone https://github.com/markhilton/redis-http-cache.git
-/usr/local/lib/php/redis-http-cache  
-  
-# Set default work directory  
-ADD scripts/* /usr/local/bin/  
-RUN chmod +x /usr/local/bin/*  
-  
-# install aliases  
-RUN echo "" >> ~/.bashrc && \  
-echo "# Load Custom Aliases" >> ~/.bashrc && \  
-echo "source /usr/local/bin/aliases.sh" >> ~/.bashrc && \  
-echo "" >> ~/.bashrc && \  
-sed -i 's/\r//' /usr/local/bin/aliases.sh && \  
-sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /usr/local/bin/aliases.sh  
-  
-# Clean up  
-RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*
-/tmp/* /var/tmp/*  
-  
-# Health check  
-HEALTHCHECK \--interval=5s --timeout=3s \  
-CMD SCRIPT_NAME=/status SCRIPT_FILENAME=/status REQUEST_METHOD=GET cgi-fcgi
--bind -connect 127.0.0.1:9000 || exit 1  
-  
-WORKDIR /var/www  
-  
-EXPOSE 9000  
-CMD ["php-fpm"]  
+FROM php:7.3-fpm
 
+RUN apt-get update -y
+RUN apt-get -y install gcc make autoconf libc-dev pkg-config libzip-dev
+
+RUN apt-get install -y --no-install-recommends \
+	git \
+	libmemcached-dev \
+	libz-dev \
+	libpq-dev \
+	libssl-dev libssl-doc libsasl2-dev \
+	libmcrypt-dev \
+	libxml2-dev \
+	zlib1g-dev libicu-dev g++ \
+	libldap2-dev libbz2-dev \
+	curl libcurl4-openssl-dev \
+	libenchant-dev libgmp-dev firebird-dev libib-util \
+	re2c libpng++-dev \
+	libwebp-dev libjpeg-dev libjpeg62-turbo-dev libpng-dev libvpx-dev libfreetype6-dev \
+	libmagick++-dev \
+	libmagickwand-dev \
+	zlib1g-dev libgd-dev \
+	libtidy-dev libxslt1-dev libmagic-dev libexif-dev file \
+	sqlite3 libsqlite3-dev libxslt-dev \
+	libmhash2 libmhash-dev libc-client-dev libkrb5-dev libssh2-1-dev \
+	unzip libpcre3 libpcre3-dev \
+	poppler-utils ghostscript libmagickwand-6.q16-dev libsnmp-dev libedit-dev libreadline6-dev libsodium-dev \
+	freetds-bin freetds-dev freetds-common libct4 libsybdb5 tdsodbc libreadline-dev librecode-dev libpspell-dev
+
+# fix for docker-php-ext-install pdo_dblib
+# https://stackoverflow.com/questions/43617752/docker-php-and-freetds-cannot-find-freetds-in-know-installation-directories
+RUN ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/
+
+RUN docker-php-ext-configure hash --with-mhash && \
+	docker-php-ext-install hash
+RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
+	docker-php-ext-install imap iconv
+
+RUN docker-php-ext-install bcmath bz2 calendar ctype curl dba dom enchant
+RUN docker-php-ext-install fileinfo exif ftp gettext gmp
+RUN docker-php-ext-install interbase intl json ldap mbstring mysqli
+RUN docker-php-ext-install opcache pcntl pspell
+RUN docker-php-ext-install pdo pdo_dblib pdo_mysql pdo_pgsql pdo_sqlite pgsql phar posix
+RUN docker-php-ext-install readline recode
+RUN docker-php-ext-install session shmop simplexml soap sockets sodium
+RUN docker-php-ext-install sysvmsg sysvsem sysvshm
+# RUN docker-php-ext-install snmp
+
+# fix for docker-php-ext-install xmlreader
+# https://github.com/docker-library/php/issues/373
+RUN export CFLAGS="-I/usr/src/php" && docker-php-ext-install xmlreader xmlwriter xml xmlrpc xsl
+
+RUN docker-php-ext-install tidy tokenizer wddx zend_test zip
+
+# already build in... what they say...
+# RUN docker-php-ext-install filter reflection spl standard
+# RUN docker-php-ext-install pdo_firebird pdo_oci
+
+# install pecl extension
+RUN pecl install ds && \
+	pecl install imagick && \
+	pecl install igbinary && \
+	pecl install redis && \
+	pecl install memcached && \
+	docker-php-ext-enable ds imagick igbinary redis memcached
+
+# https://serverpilot.io/docs/how-to-install-the-php-ssh2-extension
+# 	pecl install ssh2-1.1.2 && \
+# docker-php-ext-enable ssh2
+
+# install pecl extension
+RUN pecl install mongodb && docker-php-ext-enable mongodb
+
+# install xdebug
+# RUN pecl install xdebug && docker-php-ext-enable xdebug
+
+RUN yes "" | pecl install msgpack && \
+	docker-php-ext-enable msgpack
+
+# install APCu
+RUN pecl install apcu && \
+	docker-php-ext-enable apcu --ini-name docker-php-ext-10-apcu.ini
+
+RUN apt-get update -y && apt-get install -y apt-transport-https locales gnupg
+
+# install MSSQL support and ODBC driver
+# RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
+# 	curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
+# 	export DEBIAN_FRONTEND=noninteractive && apt-get update -y && \
+# 	ACCEPT_EULA=Y apt-get install -y msodbcsql unixodbc-dev
+# RUN set -xe \
+# 	&& pecl install pdo_sqlsrv \
+# 	&& docker-php-ext-enable pdo_sqlsrv \
+# 	&& apt-get purge -y unixodbc-dev && apt-get autoremove -y && apt-get clean
+
+# RUN docker-php-ext-configure spl && docker-php-ext-install spl
+
+# install GD
+RUN docker-php-ext-configure gd \
+	--with-png-dir \
+	--with-jpeg-dir \
+	--with-xpm-dir \
+	--with-webp-dir \
+	--with-freetype-dir \
+	&& docker-php-ext-install -j$(nproc) gd
+
+
+# set locale to utf-8
+RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
+ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
+
+#--------------------------------------------------------------------------
+# Final Touches
+#--------------------------------------------------------------------------
+
+# install required libs for health check
+RUN apt-get -y install libfcgi0ldbl nano htop iotop lsof mariadb-client
+
+# install composer
+RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+	&& php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
+	&& php composer-setup.php \
+	&& php -r "unlink('composer-setup.php');" \
+	&& mv composer.phar /usr/local/sbin/composer \
+	&& chmod +x /usr/local/sbin/composer
+
+# install NewRelic agent
+RUN echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list && \
+	curl https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
+	apt-get -y update && \
+	DEBIAN_FRONTEND=noninteractive apt-get -y install newrelic-php5 newrelic-sysmond && \
+	export NR_INSTALL_SILENT=1 && newrelic-install install
+
+# install SendGrid
+RUN echo "postfix postfix/mailname string localhost" | debconf-set-selections && \
+	echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections && \
+	DEBIAN_FRONTEND=noninteractive apt-get install postfix libsasl2-modules -y
+
+# Set default work directory
+ADD scripts/* /usr/local/bin/
+RUN chmod +x  /usr/local/bin/*
+
+# Add default configuration files
+ADD configs/php.ini /usr/local/etc/php/
+ADD configs/www.conf /usr/local/etc/php-fpm.d/
+
+# Health check
+RUN echo '#!/bin/bash' > /healthcheck && \
+	echo 'SCRIPT_NAME=/health SCRIPT_FILENAME=/health REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1' >> /healthcheck && \
+	chmod +x /healthcheck
+
+# Clean up
+RUN apt-get remove -y git && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
diff --git a/data/c/csd1/erlang-otp-elixir-ruby/Dockerfile b/data/c/csd1/erlang-otp-elixir-ruby/Dockerfile
--- a/data/c/csd1/erlang-otp-elixir-ruby/Dockerfile
+++ b/data/c/csd1/erlang-otp-elixir-ruby/Dockerfile
@@ -1,227 +1,189 @@
-FROM golang:1.9-alpine as build  
-  
-RUN apk add -U bash git make  
-RUN go get github.com/Shopify/ejson \  
-&& (cd /go/src/github.com/Shopify/ejson; make binaries)  
-  
-FROM alpine:3.7  
-##############  
-## Versions ##  
-##############  
-# elixir expects utf8.  
-ENV OTP_VERSION="20.3.2" \  
-OTP_DOWNLOAD_SHA256=9809be52baa23d6fd18ee70b9a9b7c548e44f586db2f46ff5bfe66719cfab10a
-\  
-ELIXIR_VERSION="v1.6.4" \  
-ELIXIR_DOWNLOAD_SHA256=3a081c07d8ea2ce6620201e2689ce1fac0ee937ba5c13670cbaa40349e1581ab
-\  
-LANG=C.UTF-8 \  
-RUBY_MAJOR=2.4 \  
-RUBY_VERSION=2.4.1 \  
-RUBY_DOWNLOAD_SHA256=4fc8a9992de3e90191de369270ea4b6c1b171b7941743614cc50822ddc1fe654
-\  
-RUBYGEMS_VERSION=2.6.13 \  
-BUNDLER_VERSION=1.15.4  
-############  
-## Erlang ##  
-############  
-  
-RUN set -xe \  
-&&
-OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz"
-\  
-&& apk add --no-cache --virtual .fetch-deps \  
-curl \  
-ca-certificates \  
-&& curl -fSL -o otp-src.tar.gz "$OTP_DOWNLOAD_URL" \  
-&& echo "$OTP_DOWNLOAD_SHA256 otp-src.tar.gz" | sha256sum -c - \  
-&& apk add --no-cache --virtual .build-deps \  
-dpkg-dev dpkg \  
-gcc \  
-g++ \  
-libc-dev \  
-linux-headers \  
-make \  
-autoconf \  
-ncurses-dev \  
-openssl-dev \  
-unixodbc-dev \  
-lksctp-tools-dev \  
-tar \  
-&& export ERL_TOP="/usr/src/otp_src_${OTP_VERSION%%@*}" \  
-&& mkdir -vp $ERL_TOP \  
-&& tar -xzf otp-src.tar.gz -C $ERL_TOP --strip-components=1 \  
-&& rm otp-src.tar.gz \  
-&& ( cd $ERL_TOP \  
-&& ./otp_build autoconf \  
-&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \  
-&& ./configure --build="$gnuArch" \  
-&& make -j$(getconf _NPROCESSORS_ONLN) \  
-&& make install ) \  
-&& rm -rf $ERL_TOP \  
-&& find /usr/local -regex
-'/usr/local/lib/erlang/\\(lib/\|erts-\\).*/\\(man\|doc\|obj\|c_src\|emacs\|info\|examples\\)'
-| xargs rm -rf \  
-&& find /usr/local -name src | xargs -r find | grep -v '\\.hrl$' | xargs rm -v
-|| true \  
-&& find /usr/local -name src | xargs -r find | xargs rmdir -vp || true \  
-&& scanelf --nobanner -E ET_EXEC -BF '%F' \--recursive /usr/local | xargs -r
-strip --strip-all \  
-&& scanelf --nobanner -E ET_DYN -BF '%F' \--recursive /usr/local | xargs -r
-strip --strip-unneeded \  
-&& runDeps="$( \  
-scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \  
-| tr ',' '\n' \  
-| sort -u \  
-| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1
-}' \  
-)" \  
-&& apk add --virtual .erlang-rundeps $runDeps lksctp-tools \  
-&& apk del .fetch-deps .build-deps  
-  
-############  
-## Elixir ##  
-############  
-  
-RUN set -xe \  
-&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-
-lang/elixir/releases/download/${ELIXIR_VERSION}/Precompiled.zip" \  
-&& buildDeps=' \  
-ca-certificates \  
-curl \  
-unzip \  
-' \  
-&& apk add --no-cache --virtual .build-deps $buildDeps \  
-&& curl -fSL -o elixir-precompiled.zip $ELIXIR_DOWNLOAD_URL \  
-&& echo "$ELIXIR_DOWNLOAD_SHA256 elixir-precompiled.zip" | sha256sum -c - \  
-&& unzip -d /usr/local elixir-precompiled.zip \  
-&& rm elixir-precompiled.zip \  
-&& apk del .build-deps  
-  
-###########  
-## Ruby ##  
-###########  
-  
-RUN mkdir -p /usr/local/etc \  
-&& { \  
-echo 'install: --no-document'; \  
-echo 'update: --no-document'; \  
-} >> /usr/local/etc/gemrc  
-  
-# some of ruby's build scripts are written in ruby  
-# we purge system ruby later to make sure our final image uses what we just
-built  
-# readline-dev vs libedit-dev: https://bugs.ruby-lang.org/issues/11869 and
-https://github.com/docker-library/ruby/issues/75  
-RUN set -ex \  
-\  
-&& apk add --no-cache --virtual .ruby-builddeps \  
-autoconf \  
-bison \  
-bzip2 \  
-bzip2-dev \  
-ca-certificates \  
-coreutils \  
-dpkg-dev dpkg \  
-gcc \  
-gdbm-dev \  
-glib-dev \  
-libc-dev \  
-libffi-dev \  
-libressl \  
-libressl-dev \  
-libxml2-dev \  
-libxslt-dev \  
-linux-headers \  
-make \  
-ncurses-dev \  
-procps \  
-readline-dev \  
-ruby \  
-tar \  
-xz \  
-yaml-dev \  
-zlib-dev \  
-\  
-&& wget -O ruby.tar.xz "https://cache.ruby-
-lang.org/pub/ruby/${RUBY_MAJOR%-rc}/ruby-$RUBY_VERSION.tar.xz" \  
-&& echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.xz" | sha256sum -c - \  
-\  
-&& mkdir -p /usr/src/ruby \  
-&& tar -xJf ruby.tar.xz -C /usr/src/ruby --strip-components=1 \  
-&& rm ruby.tar.xz \  
-\  
-&& cd /usr/src/ruby \  
-\  
-# hack in "ENABLE_PATH_CHECK" disabling to suppress:  
-# warning: Insecure world writable dir  
-&& { \  
-echo '#define ENABLE_PATH_CHECK 0'; \  
-echo; \  
-cat file.c; \  
-} > file.c.new \  
-&& mv file.c.new file.c \  
-\  
-&& autoconf \  
-&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \  
-# the configure script does not detect isnan/isinf as macros  
-&& export ac_cv_func_isnan=yes ac_cv_func_isinf=yes \  
-&& ./configure \  
-\--build="$gnuArch" \  
-\--disable-install-doc \  
-\--enable-shared \  
-&& make -j "$(nproc)" \  
-&& make install \  
-\  
-&& runDeps="$( \  
-scanelf --needed --nobanner --recursive /usr/local \  
-| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \  
-| sort -u \  
-| xargs -r apk info --installed \  
-| sort -u \  
-)" \  
-&& apk add --virtual .ruby-rundeps $runDeps \  
-bzip2 \  
-ca-certificates \  
-libffi-dev \  
-libressl-dev \  
-procps \  
-yaml-dev \  
-zlib-dev \  
-&& apk del .ruby-builddeps \  
-&& cd / \  
-&& rm -r /usr/src/ruby \  
-\  
-&& gem update --system "$RUBYGEMS_VERSION" \  
-&& gem install bundler --version "$BUNDLER_VERSION"  
-  
-# install things globally, for great justice  
-# and don't create ".bundle" in all our apps  
-ENV GEM_HOME=/usr/local/bundle \  
-BUNDLE_PATH="/usr/local/bundle" \  
-BUNDLE_BIN="/usr/local/bundle/bin" \  
-BUNDLE_SILENCE_ROOT_WARNING=1 \  
-BUNDLE_APP_CONFIG="/usr/local/bundle" \  
-PATH=/usr/local/bundle/bin:$PATH  
-RUN mkdir -p "$GEM_HOME" "$BUNDLE_BIN" \  
-&& chmod 777 "$GEM_HOME" "$BUNDLE_BIN"  
-####################  
-## Customizations ##  
-####################  
-#########################  
-## Common Runtime Deps ##  
-#########################  
-  
-COPY --from=build /go/src/github.com/Shopify/ejson/build/bin/linux-amd64
-/usr/local/bin/ejson  
-  
-# coreutils below is needed as of 2/16/2018  
-# `env` seems to be broken with `-u` which  
-# is used in the load_env script  
-RUN mix local.hex --force \  
-&& mix local.rebar --force \  
-&& commonDeps='coreutils libpq tzdata ca-certificates bash jq imagemagick' \  
-&& apk add -U --no-cache --virtual .common-deps $commonDeps  
-  
-CMD ["iex"]  
+FROM golang:1.9-alpine as build
 
+RUN apk add -U bash git make
+RUN go get github.com/Shopify/ejson \
+    && (cd /go/src/github.com/Shopify/ejson; make binaries)
+
+# Release Image
+FROM debian:stretch
+
+ENV GEM_HOME /usr/local/bundle
+ENV BUNDLE_PATH "$GEM_HOME"
+ENV RUBY_MAJOR=2.5 \
+    RUBY_VERSION=2.5.1 \
+    RUBY_DOWNLOAD_SHA256=886ac5eed41e3b5fc699be837b0087a6a5a3d10f464087560d2d21b3e71b754d \
+    RUBYGEMS_VERSION=2.7.7 \
+    BUNDLER_VERSION=1.16.3 \
+# install things globally, for great justice
+# and don't create ".bundle" in all our apps
+    GEM_HOME=/usr/local/bundle \
+    BUNDLE_SILENCE_ROOT_WARNING=1 \
+    BUNDLE_APP_CONFIG="$GEM_HOME" \
+# path recommendation: https://github.com/bundler/bundler/pull/6469#issuecomment-383235438
+    PATH=$GEM_HOME/bin:$BUNDLE_PATH/gems/bin:$PATH \
+    OTP_VERSION=21.1 \
+    OTP_DOWNLOAD_SHA256=7212f895ae317fa7a086fa2946070de5b910df5d41263e357d44b0f1f410af0f \
+# elixir expects utf8.
+    ELIXIR_VERSION=v1.7.3 \
+    ELIXIR_DOWNLOAD_SHA256=2ea1eef6751c54b475225f20caaad20702c198fbddff1cb1513b03aee25a5f90 \
+    LANG=C.UTF-8
+
+RUN set -ex \
+	\
+        && runtimeDeps='libpq5 ca-certificates jq imagemagick' \
+        && rubyRuntimeDeps=' \
+		bzip2 \
+		ca-certificates \
+		libffi-dev \
+		libgdbm3 \
+		libssl-dev \
+		libyaml-dev \
+		procps \
+		zlib1g-dev \
+        ' \
+# some of ruby's build scripts are written in ruby
+#   we purge system ruby later to make sure our final image uses what we just built
+	&& rubyBuildDeps=' \
+		autoconf \
+		bison \
+		dpkg-dev \
+		gcc \
+		libbz2-dev \
+		libgdbm-dev \
+		libglib2.0-dev \
+		libncurses-dev \
+		libreadline-dev \
+		libxml2-dev \
+		libxslt-dev \
+		make \
+		ruby \
+		wget \
+		xz-utils \
+	' \
+	&& erlangRuntimeDeps=' \
+		libodbc1 \
+		libssl1.1 \
+		libsctp1 \
+	' \
+	&& erlangBuildDeps=' \
+		autoconf \
+		dpkg-dev \
+		gcc \
+		g++ \
+		make \
+		libncurses-dev \
+		unixodbc-dev \
+		libssl-dev \
+		libsctp-dev \
+	' \
+	&& erlangFetchDeps=' \
+		curl \
+		ca-certificates' \
+	&& elixirBuildDeps=' \
+		ca-certificates \
+		curl \
+		unzip \
+	' \
+	&& apt-get update \
+	&& apt-get install -y --no-install-recommends $erlangFetchDeps \
+	&& apt-get install -y --no-install-recommends $runtimeDeps $rubyRuntimeDeps $erlangRuntimeDeps \
+	&& apt-get install -y --no-install-recommends $rubyBuildDeps $erlangBuildDeps $elixirBuildDeps \
+##########
+# Ruby
+# https://github.com/docker-library/ruby/blob/eca972d167cf4291de898e85aaf50d9a1929d4c7/2.5/stretch/slim/Dockerfile
+##########
+# skip installing gem documentation
+      && mkdir -p /usr/local/etc \
+	&& { \
+		echo 'install: --no-document'; \
+		echo 'update: --no-document'; \
+	} >> /usr/local/etc/gemrc \
+	\
+	&& wget -O ruby.tar.xz "https://cache.ruby-lang.org/pub/ruby/${RUBY_MAJOR%-rc}/ruby-$RUBY_VERSION.tar.xz" \
+	&& echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.xz" | sha256sum -c - \
+	\
+	&& mkdir -p /usr/src/ruby \
+	&& tar -xJf ruby.tar.xz -C /usr/src/ruby --strip-components=1 \
+	&& rm ruby.tar.xz \
+	\
+	&& cd /usr/src/ruby \
+	\
+# hack in "ENABLE_PATH_CHECK" disabling to suppress:
+#   warning: Insecure world writable dir
+	&& { \
+		echo '#define ENABLE_PATH_CHECK 0'; \
+		echo; \
+		cat file.c; \
+	} > file.c.new \
+	&& mv file.c.new file.c \
+	\
+	&& autoconf \
+	&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
+	&& ./configure \
+		--build="$gnuArch" \
+		--disable-install-doc \
+		--enable-shared \
+	&& make -j "$(nproc)" \
+	&& make install \
+	\
+	&& dpkg-query --show --showformat '${package}\n' \
+		| grep -P '^libreadline\d+$' \
+		| xargs apt-mark manual \
+	&& cd / \
+	&& rm -r /usr/src/ruby \
+	\
+	&& gem update --system "$RUBYGEMS_VERSION" \
+	&& gem install bundler --version "$BUNDLER_VERSION" --force \
+	&& rm -r /root/.gem/ \
+# adjust permissions of a few directories for running "gem install" as an arbitrary user
+        && mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME" \
+# (BUNDLE_PATH = GEM_HOME, no need to mkdir/chown both)
+##########
+# Erlang
+# https://github.com/erlang/docker-erlang-otp/blob/fe505cb6aa9afc509add31825b7f1734a0163c04/21/slim/Dockerfile
+##########
+	&& OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz" \
+	&& curl -fSL -o otp-src.tar.gz "$OTP_DOWNLOAD_URL" \
+	&& echo "$OTP_DOWNLOAD_SHA256  otp-src.tar.gz" | sha256sum -c - \
+	&& export ERL_TOP="/usr/src/otp_src_${OTP_VERSION%%@*}" \
+	&& mkdir -vp $ERL_TOP \
+	&& tar -xzf otp-src.tar.gz -C $ERL_TOP --strip-components=1 \
+	&& rm otp-src.tar.gz \
+	&& ( cd $ERL_TOP \
+	  && ./otp_build autoconf \
+	  && gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
+	  && ./configure --build="$gnuArch" \
+	  && make -j$(nproc) \
+	  && make install ) \
+	&& find /usr/local -name examples | xargs rm -rf \
+##########
+# Elixir
+# https://github.com/c0b/docker-elixir/blob/a502dfaf78efdf61ec82419c190741df293c0b29/1.7/slim/Dockerfile
+##########
+        && ELIXIR_DOWNLOAD_URL="https://repo.hex.pm/builds/elixir/$ELIXIR_VERSION-otp-$(echo $OTP_VERSION | cut -d. -f1).zip" \
+	&& curl -fSL -o elixir-precompiled.zip $ELIXIR_DOWNLOAD_URL \
+	&& echo "$ELIXIR_DOWNLOAD_SHA256  elixir-precompiled.zip" | sha256sum -c - \
+	&& unzip -d /usr/local elixir-precompiled.zip \
+	&& rm elixir-precompiled.zip \
+##########
+# Cleanup
+##########
+	&& apt-get purge -y --auto-remove $rubyBuildDeps $erlangBuildDeps $erlangFetchDeps $elixirBuildDeps \
+        ## Reinstall runtime deps in case removing build deps removed an important runtime dep
+	&& apt-get install -y --no-install-recommends $runtimeDeps $rubyRuntimeDeps $erlangRuntimeDeps \
+	&& rm -rf /var/lib/apt/lists/*
+
+##########
+##########
+##########
+
+
+
+# Customizations
+
+COPY --from=build /go/src/github.com/Shopify/ejson/build/bin/linux-amd64 /usr/local/bin/ejson
+
+RUN mix local.hex --force \
+    && mix local.rebar --force
+
+CMD ["iex"]
diff --git a/data/d/dantesignal31/vdist-aux/Dockerfile b/data/d/dantesignal31/vdist-aux/Dockerfile
--- a/data/d/dantesignal31/vdist-aux/Dockerfile
+++ b/data/d/dantesignal31/vdist-aux/Dockerfile
@@ -1,20 +1,21 @@
-FROM debian:wheezy  
-MAINTAINER dante-signal31 (dante.signal31@gmail.com)  
-# Abort on error.  
-RUN set -e  
-# Sometimes deb-src repositories comes disabled by default, we're activating
-it  
-# to use them for apt-get build-dep.  
-RUN printf "deb-src http://deb.debian.org/debian wheezy main \ndeb-src
-http://deb.debian.org/debian wheezy-updates main\ndeb-src
-http://security.debian.org wheezy/updates main\n" >> /etc/apt/sources.list  
-# Install build tools.  
-RUN apt-get update  
-RUN apt-get install ruby-dev build-essential git python-virtualenv curl
-libssl-dev libsqlite3-dev libgdbm-dev libreadline-dev libbz2-dev
-libncurses5-dev tk-dev python3 python3-pip -y  
-# Preload useful dependencies to compile python distributions.  
-RUN apt-get build-dep python python3 -y  
-# FPM installation to bundle app built directories into a system package file.  
-RUN gem install fpm
+FROM dantesignal31/vdist-aux:centos7
+LABEL maintainer="dante-signal31 (dante.signal31@gmail.com)"
+LABEL description="Don't use this image. It's only for vdist testing."
 
+# Abort on error.
+RUN set -e
+
+# Download and compile what is going to be the Python we are going to use
+# as our "custom" portable python environment.
+ARG PYTHON_VERSION=3.7.5
+ARG PYTHON_BASEDIR=/root/custom_python
+RUN mkdir -p $PYTHON_BASEDIR
+RUN yum -y --nogpgcheck update && \
+    # Since Python 3.7 you need libffi to compile it.
+    yum -y install libffi-devel && \
+    cd /var/tmp && \
+    curl -O https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz && \
+    tar xzvf Python-$PYTHON_VERSION.tgz && \
+    cd Python-$PYTHON_VERSION && \
+    ./configure --prefix=$PYTHON_BASEDIR --with-ensurepip=install && \
+    make && make install
diff --git a/data/d/dheaps/mythbackend/Dockerfile b/data/d/dheaps/mythbackend/Dockerfile
--- a/data/d/dheaps/mythbackend/Dockerfile
+++ b/data/d/dheaps/mythbackend/Dockerfile
@@ -1,20 +1,23 @@
-FROM dheaps/mythbackend:mythbuntu  
-  
-EXPOSE 80  
-# Add files  
-COPY files /root/  
-# Install mythtvweb  
-RUN apt-get install -y --no-install-recommends mythweb && \  
-a2enmod headers && \  
-a2enmod auth_digest && \  
-# clean up  
-apt-get clean && \  
-rm -rf /tmp/* /var/tmp/* \  
-/usr/share/man /usr/share/groff /usr/share/info \  
-/usr/share/lintian /usr/share/linda /var/cache/man && \  
-(( find /usr/share/doc -depth -type f ! -name copyright|xargs rm || true )) &&
-\  
-(( find /usr/share/doc -empty|xargs rmdir || true ))  
-  
-CMD ["/root/dockerentry.sh"]
+FROM dheaps/mythbackend:latest
 
+# Add files
+COPY files /root/
+
+EXPOSE 3389
+
+# install RDP environment 
+RUN apt-get install -y xrdp supervisor && \
+    apt-get install -y --no-install-recommends mate-desktop-environment && \
+	mv /root/xrdp.ini /etc/xrdp/xrdp.ini && \
+# install HD Homerun Utilities
+	apt-get install -y --no-install-recommends \
+	hdhomerun-config hdhomerun-config-gui && \
+# clean up
+	apt-get clean && \
+	rm -rf /tmp/* /var/tmp/* \
+	/usr/share/man /usr/share/groff /usr/share/info \
+	/usr/share/lintian /usr/share/linda /var/cache/man && \
+	(( find /usr/share/doc -depth -type f ! -name copyright|xargs rm || true )) && \
+	(( find /usr/share/doc -empty|xargs rmdir || true ))
+
+CMD ["/root/dockerentry.sh"]
diff --git a/data/e/errordeveloper/devenv-yocto/Dockerfile b/data/e/errordeveloper/devenv-yocto/Dockerfile
--- a/data/e/errordeveloper/devenv-yocto/Dockerfile
+++ b/data/e/errordeveloper/devenv-yocto/Dockerfile
@@ -1,7 +1,6 @@
-FROM errordeveloper/devenv-yocto:base  
-  
-ENV CHACHE_REPOS git://git.yoctoproject.org/poky  
-RUN mkdir -p repos  
-RUN bash -c 'cd repos/; for repo in ${CHACHE_REPOS}; do (git clone --quiet
---bare --mirror $repo || echo "Failed to clone $repo"); done'  
+FROM errordeveloper/devenv-yocto:base
 
+ENV CHACHE_REPOS git://git.yoctoproject.org/poky
+
+RUN mkdir -p repos
+RUN bash -c 'cd repos/; for repo in ${CHACHE_REPOS}; do (git clone --quiet --bare --mirror $repo || echo "Failed to clone $repo"); done'
diff --git a/data/f/flhosp/dropwizard/Dockerfile b/data/f/flhosp/dropwizard/Dockerfile
--- a/data/f/flhosp/dropwizard/Dockerfile
+++ b/data/f/flhosp/dropwizard/Dockerfile
@@ -1,6 +1,4 @@
-FROM flhosp/gradle  
-  
-ADD . /app  
-RUN gradle jacocoRootReport && gradle build && gradle build --stacktrace ||
-echo "There was an error"  
+FROM flhosp/gradle
 
+ADD . /app
+RUN gradle jacocoRootReport && gradle build && gradle build --stacktrace || echo "There was an error"
diff --git a/data/f/freeipa/freeipa-server/Dockerfile b/data/f/freeipa/freeipa-server/Dockerfile
--- a/data/f/freeipa/freeipa-server/Dockerfile
+++ b/data/f/freeipa/freeipa-server/Dockerfile
@@ -1,113 +1,105 @@
-# Clone from the Fedora 26 image  
-FROM registry.fedoraproject.org/fedora:26  
-MAINTAINER FreeIPA Developers <freeipa-devel@lists.fedorahosted.org>  
-  
-RUN mkdir -p /run/lock && dnf install -y freeipa-server freeipa-server-dns
-freeipa-server-trust-ad initscripts && dnf clean all  
-  
-RUN mkdir -p /var/lib/dbus && ln -s /etc/machine-id /var/lib/dbus/machine-id  
-# Workaround 1364139  
-RUN sed -i '/installutils.verify_fqdn(config.master_host_name,
-options.no_host_dns)/s/)/, local_hostname=False)/' /usr/lib/python2.7/site-
-packages/ipaserver/install/server/replicainstall.py && python -m compileall
-/usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py  
-# Workaround 1377973  
-RUN sed -i 's/ips.append(ipautil.CheckedIPAddress(ha,
-match_local=True))/ips.append(ipautil.CheckedIPAddress(ha,
-match_local=False))/' /usr/lib/python2.7/site-
-packages/ipaserver/install/installutils.py && python -m compileall
-/usr/lib/python2.7/site-packages/ipaserver/install/installutils.py  
-RUN sed -i "s/(list, 'ip-local')/(list, 'ip')/" /usr/lib/python2.7/site-
-packages/ipaserver/install/server/common.py && python -m compileall
-/usr/lib/python2.7/site-packages/ipaserver/install/server/common.py  
-# Workaround https://fedorahosted.org/freeipa/ticket/6518  
-RUN sed -i 's/getaddrinfo(fqdn/getaddrinfo(fqdn.rstrip(".")/'
-/usr/lib/python2.7/site-packages/ipaserver/install/installutils.py && python
--m compileall /usr/lib/python2.7/site-
-packages/ipaserver/install/installutils.py  
-# Workaround https://fedorahosted.org/spin-kickstarts/ticket/60  
-RUN [ -L /etc/systemd/system/syslog.service ] && ! [ -f
-/etc/systemd/system/syslog.service ] && rm -f
-/etc/systemd/system/syslog.service  
-  
-RUN find /etc/systemd/system/* '!' -name '*.wants' | xargs rm -rvf  
-RUN for i in basic.target network.service netconsole.service ; do rm -f
-/usr/lib/systemd/system/$i && ln -s /dev/null /usr/lib/systemd/system/$i ;
-done  
-RUN rm -fv /usr/lib/systemd/system/sysinit.target.wants/*  
-RUN echo 'disable *' > /usr/lib/systemd/system-preset/10-container-
-disable.preset  
-  
-RUN /sbin/ldconfig -X  
-  
-COPY init-data /usr/local/sbin/init  
-COPY ipa-server-configure-first ipa-server-status-check exit-with-status ipa-
-volume-upgrade-* /usr/sbin/  
-COPY install.sh uninstall.sh /bin/  
-RUN mv /bin/hostnamectl /bin/hostnamectl.orig  
-RUN mv /usr/bin/domainname /usr/bin/domainname.orig  
-ADD hostnamectl-wrapper /bin/hostnamectl  
-ADD hostnamectl-wrapper /usr/bin/domainname  
-RUN chmod -v +x /usr/local/sbin/init /usr/sbin/ipa-server-configure-first
-/usr/sbin/ipa-server-status-check /usr/sbin/exit-with-status /usr/sbin/ipa-
-volume-upgrade-* /bin/install.sh /bin/uninstall.sh /bin/hostnamectl
-/usr/bin/domainname  
-COPY container-ipa.target ipa-server-configure-first.service ipa-server-
-upgrade.service ipa-server-update-self-ip-address.service
-/usr/lib/systemd/system/  
-RUN rmdir -v /etc/systemd/system/multi-user.target.wants \  
-&& mkdir /etc/systemd/system/container-ipa.target.wants \  
-&& ln -s /etc/systemd/system/container-ipa.target.wants
-/etc/systemd/system/multi-user.target.wants  
-  
-RUN systemctl set-default container-ipa.target  
-RUN systemctl enable ipa-server-configure-first.service  
-  
-COPY exit-via-chroot.conf /usr/lib/systemd/system/systemd-poweroff.service.d/  
-  
-RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User'
--d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy  
-  
-COPY atomic-install-help /usr/share/ipa/  
-COPY volume-data-list volume-data-mv-list volume-data-autoupdate /etc/  
-RUN set -e ; cd / ; mkdir /data-template ; cat /etc/volume-data-list | while
-read i ; do echo $i ; if [ -e $i ] ; then tar cf - .$i | ( cd /data-template
-&& tar xf - ) ; else mkdir -p /data-template$( dirname $i ) ; fi ; mkdir -p $(
-dirname $i ) ; if [ "$i" == /var/log/ ] ; then mv /var/log /var/log-removed ;
-else rm -rf $i ; fi ; ln -sf /data${i%/} ${i%/} ; done  
-RUN rm -rf /var/log-removed  
-RUN sed -i 's!^d /var/log.*!L /var/log - - - - /data/var/log!'
-/usr/lib/tmpfiles.d/var.conf  
-# Workaround 1286602  
-RUN mv /usr/lib/tmpfiles.d/journal-nocow.conf /usr/lib/tmpfiles.d/journal-
-nocow.conf.disabled  
-RUN rm -f /data-template/var/lib/systemd/random-seed  
-RUN echo 1.1 > /etc/volume-version  
-  
-ENV container docker  
-  
-EXPOSE 53/udp 53 80 443 389 636 88 464 88/udp 464/udp 123/udp 7389 9443 9444
-9445  
-VOLUME [ "/tmp", "/run", "/data" ]  
-  
-STOPSIGNAL RTMIN+3  
-ENTRYPOINT [ "/usr/local/sbin/init" ]  
-RUN uuidgen > /data-template/build-id  
-  
-# Invocation:  
-# docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp
--v /opt/ipa-data:/data:Z -h ipa.example.test ${NAME} [ options ]  
-# For atomic, we run INSTALL --privileged but install.sh will start another
-unprivileged container.  
-# We do it this way to be able to set hostname for the unprivileged container.  
-LABEL install 'docker run -ti --rm --privileged -v /:/host -e HOST=/host -e
-DATADIR=/var/lib/${NAME} -e NAME=${NAME} -e IMAGE=${IMAGE} ${IMAGE}
-/bin/install.sh'  
-LABEL run 'docker run ${RUN_OPTS} --name ${NAME} -v /var/lib/${NAME}:/data:Z
--v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v
-/dev/urandom:/dev/random:ro ${IMAGE}'  
-LABEL RUN_OPTS_FILE '/var/lib/${NAME}/docker-run-opts'  
-LABEL stop 'docker stop ${NAME}'  
-LABEL uninstall 'docker run --rm --privileged -v /:/host -e HOST=/host -e
-DATADIR=/var/lib/${NAME} ${IMAGE} /bin/uninstall.sh'  
+# Clone from the Fedora 31 image
+FROM registry.fedoraproject.org/fedora:31
 
+MAINTAINER FreeIPA Developers <freeipa-devel@lists.fedorahosted.org>
+
+RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
+RUN groupadd -g 289 ipaapi; useradd -u 289 -g 289 -c 'IPA Framework User' -r -d / -s '/sbin/nologin' ipaapi
+
+# Workaround 1615948
+RUN ln -s /bin/false /usr/sbin/systemd-machine-id-setup
+RUN dnf upgrade -y --setopt=install_weak_deps=False \
+	&& dnf install -y --setopt=install_weak_deps=False freeipa-server freeipa-server-dns freeipa-server-trust-ad patch \
+	&& dnf clean all
+
+# debug: RUN test $( getent passwd | grep -E "^(dirsrv:x:389|ipaapi:x:289|kdcproxy:x:288|pkiuser:x:17):" | wc -l ) -eq 4
+
+# var-lib-nfs-rpc_pipefs.mount would run (and fail) nondeterministically
+RUN systemctl mask rpc-gssd.service
+
+# Container image which runs systemd
+# debug: RUN test -f /etc/machine-id && ! test -s /etc/machine-id
+# debug: RUN test "$container" = oci
+
+# Establish reasonably low open files limit in the container
+RUN echo "DefaultLimitNOFILE=1024" >> /etc/systemd/system.conf
+
+ENTRYPOINT [ "/usr/sbin/init" ]
+STOPSIGNAL RTMIN+3
+RUN mkdir /var/log/journal
+# test-addon: VOLUME [ "/var/log/journal" ]
+# test: systemd-container-failed.sh
+
+# Minimize the systemd setup
+RUN find /etc/systemd/system /usr/lib/systemd/system/{basic,multi-user,sysinit}.target.wants -type l | xargs rm -v
+COPY patches/minimal-fedora-31.patch /root/
+RUN patch --verbose -p0 --fuzz=0 < /root/minimal-fedora-31.patch
+# debug: RUN ! find /etc/systemd/system /usr/lib/systemd/system/{basic,multi-user,sysinit}.target.wants /etc/tmpfiles.d -type f | grep .
+
+RUN ln -s /usr/lib/systemd/system/dbus-broker.service /usr/lib/systemd/system/dbus.service
+COPY container-ipa.target /usr/lib/systemd/system/
+RUN systemctl set-default container-ipa.target
+RUN rmdir -v /etc/systemd/system/multi-user.target.wants \
+	&& mkdir /etc/systemd/system/container-ipa.target.wants \
+	&& ln -s /etc/systemd/system/container-ipa.target.wants /etc/systemd/system/multi-user.target.wants
+RUN systemd-tmpfiles --remove --create
+# debug: RUN ! test -f /var/lib/systemd/random-seed
+# test-addon: VOLUME [ "/var/log/journal", "/var/tmp" ]
+# test: systemd-container-diff.sh list-dependencies-fedora-30.out /dev/null docker-diff-minimal-fedora-23.out
+
+# Prepare for basic ipa-server-install in container
+# Address failing nis-domainname.service in the ipa-client-install step
+RUN mv /usr/bin/nisdomainname /usr/bin/nisdomainname.orig
+ADD hostnamectl-wrapper /usr/bin/nisdomainname
+
+# test-addon: VOLUME [ "/var/log/journal" ]
+## # test: systemd-container-ipa-server-install.sh
+
+# Move configuration and data to data volume
+COPY patches/ipa-data-fedora-30.patch /root
+RUN set -o pipefail ; patch --verbose -p0 --fuzz=0 < /root/ipa-data-fedora-30.patch | tee /dev/stderr | sed -n 's/^patching file //;T;/\.py$/p' | xargs python3 -m compileall
+
+RUN mv /usr/sbin/ipa-join /usr/sbin/ipa-join.orig
+COPY ipa-join /usr/sbin/ipa-join
+
+RUN authselect select sssd with-sudo --force && mv /usr/bin/authselect /usr/bin/authselect.orig
+COPY authselect /usr/bin/authselect
+
+COPY utils/prepare-volume-template utils/populate-volume-from-template utils/extract-rpm-upgrade-scriptlets /usr/local/bin/
+COPY volume-data-list volume-tmp-list volume-data-autoupdate /etc/
+RUN /usr/local/bin/prepare-volume-template /etc/volume-data-list /data
+RUN /usr/local/bin/prepare-volume-template /etc/volume-tmp-list /tmp
+RUN /usr/local/bin/extract-rpm-upgrade-scriptlets
+
+RUN echo 2.0 > /etc/volume-version
+VOLUME [ "/tmp", "/run", "/data", "/var/log/journal" ]
+
+COPY init-data-minimal /usr/local/sbin/init
+ENTRYPOINT [ "/usr/local/sbin/init" ]
+# test: systemd-container-ipa-server-install-data.sh docker-diff-minimal-fedora-23.out
+
+# Configure master/replica upon the first invocation
+COPY init-data /usr/local/sbin/init
+COPY ipa-server-configure-first systemctl-exit-with-status ipa-volume-upgrade-* /usr/sbin/
+COPY ipa-server-configure-first.service ipa-server-upgrade.service ipa-server-update-self-ip-address.service /usr/lib/systemd/system/
+RUN ln -sv /usr/lib/systemd/system/ipa-server-configure-first.service /data-template/etc/systemd/system/container-ipa.target.wants/ipa-server-configure-first.service
+COPY exit-status.conf /usr/lib/systemd/system/systemd-poweroff.service.d/
+
+EXPOSE 53/udp 53 80 443 389 636 88 464 88/udp 464/udp 123/udp
+
+RUN uuidgen > /data-template/build-id
+
+# Invocation:
+# docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v /opt/ipa-data:/data:Z -h ipa.example.test ${NAME} [ options ]
+
+# Atomic specific bits
+COPY install.sh uninstall.sh /bin/
+COPY atomic-install-help /usr/share/ipa/
+
+# For atomic, we run INSTALL --privileged but install.sh will start another unprivileged container.
+# We do it this way to be able to set hostname for the unprivileged container.
+LABEL install 'docker run -ti --rm --privileged -v /:/host -e HOST=/host -e DATADIR=/var/lib/${NAME} -e NAME=${NAME} -e IMAGE=${IMAGE} ${IMAGE} /bin/install.sh'
+LABEL run 'docker run ${RUN_OPTS} --name ${NAME} -v /var/lib/${NAME}:/data:Z -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v /dev/urandom:/dev/random:ro ${IMAGE}'
+LABEL RUN_OPTS_FILE '/var/lib/${NAME}/docker-run-opts'
+LABEL stop 'docker stop ${NAME}'
+LABEL uninstall 'docker run --rm --privileged -v /:/host -e HOST=/host -e DATADIR=/var/lib/${NAME} ${IMAGE} /bin/uninstall.sh'
diff --git a/data/n/nextcode/builderimg-java/Dockerfile b/data/n/nextcode/builderimg-java/Dockerfile
--- a/data/n/nextcode/builderimg-java/Dockerfile
+++ b/data/n/nextcode/builderimg-java/Dockerfile
@@ -1,22 +1,37 @@
-FROM nextcode/baseimg-java:oracle-jdk10  
-  
-MAINTAINER WuXi NextCODE DevOps <devops@wuxinextcode.com>  
-  
-RUN apt-get update && \  
-apt-get install -y \--no-install-recommends git python python-pip curl lsof
-unzip && \  
-pip install virtualenv && \  
-curl -fsSL https://apt.dockerproject.org/gpg | apt-key add \- && \  
-add-apt-repository "deb https://apt.dockerproject.org/repo/
-ubuntu-$(lsb_release -cs) main" && \  
-apt-get update && \  
-apt-get -y install docker-engine && \  
-rm -rf /var/lib/apt/lists/* && \  
-locale-gen en_US.UTF-8 && \  
-groupadd builder && \  
-adduser --disabled-password --gecos "" \--ingroup builder builder  
-  
-ENV LANG en_US.UTF-8  
-ENV LANGUAGE en_US:en  
-ENV LC_ALL en_US.UTF-8  
+FROM nextcode/baseimages:jdk-8-oracle
+LABEL maintainer="WuXi NextCODE <devops@wuxinextcode.com>"
+
+RUN adduser --uid 1000 --gecos "Build User" --disabled-password builder
+
+RUN set -ex; \
+    # Install Dependencies
+      buildDeps='apt-transport-https software-properties-common gpg-agent' && \
+      apt-get update && \
+      apt-get install -y --no-install-recommends \
+        $buildDeps \
+        git \
+        curl \
+        python \
+        python-pip \
+        lsof \
+        unzip \
+      && \
+      pip install virtualenv && \
+    # Install Docker CE
+      curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add - && \
+      apt-key fingerprint 0EBFCD88 && \
+      add-apt-repository \
+        "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
+        $(lsb_release -cs) \
+        stable" \
+      && \
+      apt-get update && \
+      apt-get install -y --no-install-recommends docker-ce && \
+    # Cleanup
+      apt-get remove -y --purge --auto-remove $buildDeps && \ 
+      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+WORKDIR /home/builder
+
+USER builder
 
diff --git a/data/n/nosinovacao/nginx/Dockerfile b/data/n/nosinovacao/nginx/Dockerfile
--- a/data/n/nosinovacao/nginx/Dockerfile
+++ b/data/n/nosinovacao/nginx/Dockerfile
@@ -1,180 +1,183 @@
-FROM alpine:3.7  
-  
-LABEL maintainer="NOS Inovação <nosi.metadata@nos.pt>"  
-  
-ENV NGINX_VERSION 1.14.0  
-# Ensure git  
-RUN apk update && apk upgrade \  
-&& apk add --no-cache --virtual .build-deps bash git  
-  
-# 3rd party modules  
-RUN cd ~ \  
-&& git clone https://github.com/kvspb/nginx-auth-ldap.git \  
-&& git clone https://github.com/vozlt/nginx-module-vts.git  
-  
-RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \  
-&& CONFIG="\  
-\--prefix=/etc/nginx \  
-\--sbin-path=/usr/sbin/nginx \  
-\--modules-path=/usr/lib/nginx/modules \  
-\--conf-path=/etc/nginx/nginx.conf \  
-\--error-log-path=/var/log/nginx/error.log \  
-\--http-log-path=/var/log/nginx/access.log \  
-\--pid-path=/var/run/nginx.pid \  
-\--lock-path=/var/run/nginx.lock \  
-\--http-client-body-temp-path=/var/cache/nginx/client_temp \  
-\--http-proxy-temp-path=/var/cache/nginx/proxy_temp \  
-\--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \  
-\--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \  
-\--http-scgi-temp-path=/var/cache/nginx/scgi_temp \  
-\--user=nginx \  
-\--group=nginx \  
-\--with-http_ssl_module \  
-\--with-http_realip_module \  
-\--with-http_addition_module \  
-\--with-http_sub_module \  
-\--with-http_dav_module \  
-\--with-http_flv_module \  
-\--with-http_mp4_module \  
-\--with-http_gunzip_module \  
-\--with-http_gzip_static_module \  
-\--with-http_random_index_module \  
-\--with-http_secure_link_module \  
-\--with-http_stub_status_module \  
-\--with-http_auth_request_module \  
-\--with-http_xslt_module=dynamic \  
-\--with-http_image_filter_module=dynamic \  
-\--with-http_geoip_module=dynamic \  
-\--with-threads \  
-\--with-stream \  
-\--with-stream_ssl_module \  
-\--with-stream_ssl_preread_module \  
-\--with-stream_realip_module \  
-\--with-stream_geoip_module=dynamic \  
-\--with-http_slice_module \  
-\--with-mail \  
-\--with-mail_ssl_module \  
-\--with-compat \  
-\--with-file-aio \  
-\--with-http_v2_module \  
-\--add-module=/root/nginx-auth-ldap \  
-\--add-module=/root/nginx-module-vts \  
-" \  
-&& addgroup -S nginx \  
-&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \  
-&& apk add --no-cache --virtual .build-deps \  
-gcc \  
-libc-dev \  
-make \  
-#openssl-dev \ # used libressl-dev instead (openssl does not work with
-openldap)  
-libressl-dev \  
-pcre-dev \  
-zlib-dev \  
-linux-headers \  
-curl \  
-gnupg \  
-libxslt-dev \  
-gd-dev \  
-geoip-dev \  
-# openldap-dev is a dependecy for the nginx-auth-ldap module  
-openldap-dev \  
-&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o
-nginx.tar.gz \  
-&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc -o
-nginx.tar.gz.asc \  
-&& export GNUPGHOME="$(mktemp -d)" \  
-&& found=''; \  
-for server in \  
-ha.pool.sks-keyservers.net \  
-hkp://keyserver.ubuntu.com:80 \  
-hkp://p80.pool.sks-keyservers.net:80 \  
-pgp.mit.edu \  
-; do \  
-echo "Fetching GPG key $GPG_KEYS from $server"; \  
-gpg --keyserver "$server" \--keyserver-options timeout=10 \--recv-keys
-"$GPG_KEYS" && found=yes && break; \  
-done; \  
-test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" &&
-exit 1; \  
-gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \  
-&& rm -rf "$GNUPGHOME" nginx.tar.gz.asc \  
-&& mkdir -p /usr/src \  
-&& tar -zxC /usr/src -f nginx.tar.gz \  
-&& rm nginx.tar.gz \  
-&& cd /usr/src/nginx-$NGINX_VERSION \  
-&& ./configure $CONFIG --with-debug \  
-&& make -j$(getconf _NPROCESSORS_ONLN) \  
-&& mv objs/nginx objs/nginx-debug \  
-&& mv objs/ngx_http_xslt_filter_module.so objs/ngx_http_xslt_filter_module-
-debug.so \  
-&& mv objs/ngx_http_image_filter_module.so objs/ngx_http_image_filter_module-
-debug.so \  
-&& mv objs/ngx_http_geoip_module.so objs/ngx_http_geoip_module-debug.so \  
-&& mv objs/ngx_stream_geoip_module.so objs/ngx_stream_geoip_module-debug.so \  
-&& ./configure $CONFIG \  
-&& make -j$(getconf _NPROCESSORS_ONLN) \  
-&& make install \  
-&& rm -rf /etc/nginx/html/ \  
-&& mkdir /etc/nginx/conf.d/ \  
-&& mkdir -p /usr/share/nginx/html/ \  
-&& install -m644 html/index.html /usr/share/nginx/html/ \  
-&& install -m644 html/50x.html /usr/share/nginx/html/ \  
-&& install -m755 objs/nginx-debug /usr/sbin/nginx-debug \  
-&& install -m755 objs/ngx_http_xslt_filter_module-debug.so
-/usr/lib/nginx/modules/ngx_http_xslt_filter_module-debug.so \  
-&& install -m755 objs/ngx_http_image_filter_module-debug.so
-/usr/lib/nginx/modules/ngx_http_image_filter_module-debug.so \  
-&& install -m755 objs/ngx_http_geoip_module-debug.so
-/usr/lib/nginx/modules/ngx_http_geoip_module-debug.so \  
-&& install -m755 objs/ngx_stream_geoip_module-debug.so
-/usr/lib/nginx/modules/ngx_stream_geoip_module-debug.so \  
-&& ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \  
-&& strip /usr/sbin/nginx* \  
-&& strip /usr/lib/nginx/modules/*.so \  
-&& rm -rf /usr/src/nginx-$NGINX_VERSION \  
-\  
-# Bring in gettext so we can get `envsubst`, then throw  
-# the rest away. To do this, we need to install `gettext`  
-# then move `envsubst` out of the way so `gettext` can  
-# be deleted completely, then move `envsubst` back.  
-&& apk add --no-cache --virtual .gettext gettext \  
-&& mv /usr/bin/envsubst /tmp/ \  
-\  
-&& runDeps="$( \  
-scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx
-/usr/lib/nginx/modules/*.so /tmp/envsubst \  
-| tr ',' '\n' \  
-| sort -u \  
-| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1
-}' \  
-)" \  
-&& apk add --no-cache --virtual .nginx-rundeps $runDeps \  
-&& apk del .build-deps \  
-&& apk del .gettext \  
-&& mv /tmp/envsubst /usr/local/bin/ \  
-\  
-# Bring in tzdata so users could set the timezones through the environment  
-# variables  
-&& apk add --no-cache tzdata \  
-\  
-# forward request and error logs to docker log collector  
-&& ln -sf /dev/stdout /var/log/nginx/access.log \  
-&& ln -sf /dev/stderr /var/log/nginx/error.log \  
-\  
-# NOS Inovação changes  
-# Bring in bash so users can exec into the container  
-&& apk add --no-cache bash \  
-\  
-# Cleanup 3rdparty modules  
-&& rm -rf /root/nginx-*  
-  
-COPY nginx.conf /etc/nginx/nginx.conf  
-COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf  
-  
-EXPOSE 80  
-  
-STOPSIGNAL SIGTERM  
-  
-CMD ["nginx", "-g", "daemon off;"]  
+FROM alpine:3.7
 
+LABEL maintainer="NOS Inovação <nosi.metadata@nos.pt>"
+
+ENV NGINX_VERSION 1.16.1
+ENV NJS_VERSION 0.3.5
+
+# Ensure git
+RUN apk update && apk upgrade \
+	&& apk add --no-cache --virtual .build-deps bash git libmaxminddb-dev autoconf automake
+
+RUN apk add --virtual .build-deps \
+		gcc \
+		libc-dev \
+		make \
+		#openssl-dev \ # used libressl-dev instead (openssl does not work with openldap)
+		libressl-dev \
+		pcre-dev \
+		zlib-dev \
+		linux-headers \
+		curl \
+		gnupg \
+		libxslt-dev \
+		gd-dev \
+		geoip-dev \
+		# openldap-dev is a dependecy for the nginx-auth-ldap module
+		openldap-dev
+
+# 3rd party modules
+RUN cd ~ \
+	&& git clone https://github.com/kvspb/nginx-auth-ldap.git \
+	&& git clone https://github.com/vozlt/nginx-module-vts.git \
+	&& git clone https://github.com/simplresty/ngx_devel_kit.git \
+	&& git clone https://github.com/openresty/lua-nginx-module.git \
+	&& git clone https://github.com/openresty/luajit2.git \
+	&& wget http://hg.nginx.org/njs/archive/${NJS_VERSION}.tar.gz \
+	&& tar xvf ${NJS_VERSION}.tar.gz \
+	&& git clone https://github.com/leev/ngx_http_geoip2_module.git 
+
+RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
+	&& export LUAJIT_LIB=/usr/local/lib \
+	&& export LUAJIT_INC=/usr/local/include/luajit-2.1 \
+	&& CONFIG="\
+		--prefix=/etc/nginx \
+		--sbin-path=/usr/sbin/nginx \
+		--modules-path=/usr/lib/nginx/modules \
+		--conf-path=/etc/nginx/nginx.conf \
+		--error-log-path=/var/log/nginx/error.log \
+		--http-log-path=/var/log/nginx/access.log \
+		--pid-path=/var/run/nginx.pid \
+		--lock-path=/var/run/nginx.lock \
+		--http-client-body-temp-path=/var/cache/nginx/client_temp \
+		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
+		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
+		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
+		--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
+		--user=nginx \
+		--group=nginx \
+		--with-http_ssl_module \
+		--with-http_realip_module \
+		--with-http_addition_module \
+		--with-http_sub_module \
+		--with-http_dav_module \
+		--with-http_flv_module \
+		--with-http_mp4_module \
+		--with-http_gunzip_module \
+		--with-http_gzip_static_module \
+		--with-http_random_index_module \
+		--with-http_secure_link_module \
+		--with-http_stub_status_module \
+		--with-http_auth_request_module \
+		--with-http_xslt_module=dynamic \
+		--with-http_image_filter_module=dynamic \
+		--with-http_geoip_module=dynamic \
+		--with-threads \
+		--with-stream \
+		--with-stream_ssl_module \
+		--with-stream_ssl_preread_module \
+		--with-stream_realip_module \
+		--with-stream_geoip_module=dynamic \
+		--with-http_slice_module \
+		--with-mail \
+		--with-mail_ssl_module \
+		--with-compat \
+		--with-file-aio \
+		--with-http_v2_module \
+		--with-ld-opt=-Wl,-rpath,/usr/local/lib \
+		--add-module=/root/nginx-auth-ldap \
+		--add-module=/root/nginx-module-vts \
+		--add-dynamic-module=/root/njs-$NJS_VERSION/nginx \
+		--add-module=/root/ngx_devel_kit \
+		--add-dynamic-module=/root/lua-nginx-module \
+		--add-module=/root/ngx_http_geoip2_module" \
+	&& addgroup -S nginx \
+	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
+	&& cd ~/luajit2 \
+	&& make -j4 && make install && cd .. \
+	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
+	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& found=''; \
+	for server in \
+		ha.pool.sks-keyservers.net \
+		hkp://keyserver.ubuntu.com:80 \
+		hkp://p80.pool.sks-keyservers.net:80 \
+		pgp.mit.edu \
+	; do \
+		echo "Fetching GPG key $GPG_KEYS from $server"; \
+		gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+	done; \
+	test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+	gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
+	&& rm -rf "$GNUPGHOME" nginx.tar.gz.asc \
+	&& mkdir -p /usr/src \
+	&& tar -zxC /usr/src -f nginx.tar.gz \
+	&& rm nginx.tar.gz \
+	&& cd /usr/src/nginx-$NGINX_VERSION \
+	&& ./configure $CONFIG --with-debug \
+	&& make -j$(getconf _NPROCESSORS_ONLN) \
+	&& mv objs/nginx objs/nginx-debug \
+	&& mv objs/ngx_http_xslt_filter_module.so objs/ngx_http_xslt_filter_module-debug.so \
+	&& mv objs/ngx_http_image_filter_module.so objs/ngx_http_image_filter_module-debug.so \
+	&& mv objs/ngx_http_geoip_module.so objs/ngx_http_geoip_module-debug.so \
+	&& mv objs/ngx_stream_geoip_module.so objs/ngx_stream_geoip_module-debug.so \
+	&& ./configure $CONFIG \
+	&& make -j$(getconf _NPROCESSORS_ONLN) \
+	&& make install \
+	&& rm -rf /etc/nginx/html/ \
+	&& mkdir /etc/nginx/conf.d/ \
+	&& mkdir -p /usr/share/nginx/html/ \
+	&& install -m644 html/index.html /usr/share/nginx/html/ \
+	&& install -m644 html/50x.html /usr/share/nginx/html/ \
+	&& install -m755 objs/nginx-debug /usr/sbin/nginx-debug \
+	&& install -m755 objs/ngx_http_xslt_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_xslt_filter_module-debug.so \
+	&& install -m755 objs/ngx_http_image_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_image_filter_module-debug.so \
+	&& install -m755 objs/ngx_http_geoip_module-debug.so /usr/lib/nginx/modules/ngx_http_geoip_module-debug.so \
+	&& install -m755 objs/ngx_stream_geoip_module-debug.so /usr/lib/nginx/modules/ngx_stream_geoip_module-debug.so \
+	&& ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \
+	&& strip /usr/sbin/nginx* \
+	&& strip /usr/lib/nginx/modules/*.so \
+	&& rm -rf /usr/src/nginx-$NGINX_VERSION \
+	\
+	# Bring in gettext so we can get `envsubst`, then throw
+	# the rest away. To do this, we need to install `gettext`
+	# then move `envsubst` out of the way so `gettext` can
+	# be deleted completely, then move `envsubst` back.
+	&& apk add --no-cache --virtual .gettext gettext \
+	&& mv /usr/bin/envsubst /tmp/ \
+	\
+	&& runDeps="$( \
+		scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
+			| tr ',' '\n' \
+			| sort -u \
+			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+	)" \
+	&& apk add --no-cache --virtual .nginx-rundeps $runDeps \
+	&& apk del .build-deps \
+	&& apk del .gettext \
+	&& mv /tmp/envsubst /usr/local/bin/ \
+	\
+	# Bring in tzdata so users could set the timezones through the environment
+	# variables
+	&& apk add --no-cache tzdata \
+	\
+	# forward request and error logs to docker log collector
+	&& ln -sf /dev/stdout /var/log/nginx/access.log \
+	&& ln -sf /dev/stderr /var/log/nginx/error.log \
+	\
+	# NOS Inovação changes
+	# Bring in bash so users can exec into the container
+	&& apk add --no-cache bash \
+	\
+	# Cleanup 3rdparty modules
+	&& rm -rf /root/nginx-* /root/*.gz /root/lua* /root/ngx* /root/njs*
+
+COPY nginx.conf /etc/nginx/nginx.conf
+COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf
+
+EXPOSE 80
+
+STOPSIGNAL SIGTERM
+
+CMD ["nginx", "-g", "daemon off;"]
diff --git a/data/n/nutshells/base/Dockerfile b/data/n/nutshells/base/Dockerfile
--- a/data/n/nutshells/base/Dockerfile
+++ b/data/n/nutshells/base/Dockerfile
@@ -1,44 +1,44 @@
-FROM alpine:edge  
-LABEL maintainer='Chao QU <mail@quchao.com>'  
-  
-RUN set -ex; \  
-# enable edge repos  
-echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/main' >>
-/etc/apk/repositories; \  
-echo '@community http://dl-cdn.alpinelinux.org/alpine/edge/community' >>
-/etc/apk/repositories; \  
-# change mirrors  
-sed -i 's|http://dl-cdn.alpinelinux.org|https://mirrors.aliyun.com|g'
-/etc/apk/repositories; \  
-# keep update-to-date  
-apk update; \  
-apk upgrade; \  
-# runtime deps  
-apk add \--no-cache --virtual .common-deps \  
-ca-certificates@edge \  
-su-exec@edge \  
-curl@edge \  
-; \  
-# reset CA list  
-update-ca-certificates --fresh; \  
-# cleaning  
-rm -rf /tmp/* /var/tmp/* /var/cache/apk/*;  
-  
-ARG RUN_AS_USER  
-ENV RUN_AS_USER="${RUN_AS_USER:-nutshell}"  
-RUN set -ex; \  
-# a low-privilege user  
-addgroup -S "${RUN_AS_USER}"; \  
-adduser -S -D -H -h /var/empty -s /sbin/nologin -G "${RUN_AS_USER}"
-"${RUN_AS_USER}";  
-  
-COPY docker-entrypoint.sh entrypoint-utils.sh /usr/local/bin/  
-  
-RUN set -ex; \  
-# test flight  
-chmod +x /usr/local/bin/docker-entrypoint.sh;  
-  
-RUN set -ex; \  
-# avoid docker's 'Text file busy' issue  
-docker-entrypoint.sh /bin/true;  
+FROM centos
+LABEL maintainer='Chao QU <mail@quchao.com>'
 
+ARG GOSU_VERSION='1.10'
+
+RUN set -ex; \
+    # epel
+    #yum -y install epel-release; \
+    # keep up-to-date
+    yum update -y --exclude=kernel*; \
+    # gosu
+    readonly ARCH='amd64'; \
+    readonly GOSU_URL_BASE='https://github.com/tianon/gosu/releases/download/'; \
+	curl -sSL -o /usr/bin/gosu "${GOSU_URL_BASE}${GOSU_VERSION}/gosu-${ARCH}"; \
+	curl -sSL -o /tmp/gosu.asc "${GOSU_URL_BASE}${GOSU_VERSION}/gosu-${ARCH}.asc"; \
+    # verify the signature
+    readonly GPG_KEY_SRV='keys.gnupg.net'; \
+    readonly GOSU_GPG_KEY='B42F6819007F00F88E364FD4036A9C25BF357DD4'; \
+	readonly GNUPGHOME="$(mktemp -d)"; \
+	gpg --keyserver "${GPG_KEY_SRV}" --recv-keys "${GOSU_GPG_KEY}"; \
+	gpg --batch --verify /tmp/gosu.asc /usr/bin/gosu; \
+	rm -r "${GNUPGHOME}" /tmp/gosu.asc; \
+	chmod +x /usr/bin/gosu; \
+	# cleanup
+	yum clean all; \
+    rm -rf /tmp/* /var/tmp/*;
+
+ARG RUN_AS_USER
+ENV RUN_AS_USER="${RUN_AS_USER:-nutshell}"
+
+RUN set -ex; \
+    # a low-privilege user
+    groupadd -r "${RUN_AS_USER}"; \
+    useradd -M -d /var/empty -s /sbin/nologin -g "${RUN_AS_USER}" -r "${RUN_AS_USER}";
+
+COPY docker-entrypoint.sh entrypoint-utils.sh /usr/local/bin/
+
+RUN set -ex; \
+    # use gosu instead
+    sed -i 's/su-exec/gosu/' /usr/local/bin/docker-entrypoint.sh; \
+    # test flight
+	chmod +x /usr/local/bin/docker-entrypoint.sh; \
+    # avoid docker's 'Text file busy' issue
+	docker-entrypoint.sh /bin/true;
diff --git a/data/o/opensuse/portus/Dockerfile b/data/o/opensuse/portus/Dockerfile
--- a/data/o/opensuse/portus/Dockerfile
+++ b/data/o/opensuse/portus/Dockerfile
@@ -1,31 +1,40 @@
-FROM opensuse/amd64:42.3  
-MAINTAINER SUSE Containers Team <containers@suse.com>  
-  
-# Install the entrypoint of this image.  
-COPY init /  
-  
-# Install Portus and prepare the /certificates directory.  
-RUN chmod +x /init && \  
-# Fetch the key from the obs://Virtualization:containers:Portus project.  
-mkdir -m 0600 /tmp/build && \  
-gpg \--homedir /tmp/build \--keyserver ha.pool.sks-keyservers.net \--recv-keys
-55A0B34D49501BB7CA474F5AA193FBB572174FC2 && \  
-gpg \--homedir /tmp/build \--export \--armor
-55A0B34D49501BB7CA474F5AA193FBB572174FC2 > /tmp/build/repo.key && \  
-rpm \--import /tmp/build/repo.key && \  
-rm -rf /tmp/build && \  
-# Now add the repository and installa portus.  
-zypper ar -f obs://Virtualization:containers:Portus/openSUSE_Leap_42.3 portus
-&& \  
-zypper ref && \  
-zypper -n in \--from portus ruby-common portus && \  
-# Remove unneeded packages and clean stuff.  
-zypper -n rm kbd-legacy && \  
-zypper clean -a && \  
-# Prepare the certificates directory.  
-rm -rf /etc/pki/trust/anchors && \  
-ln -sf /certificates /etc/pki/trust/anchors  
-  
-EXPOSE 3000  
-ENTRYPOINT ["/init"]  
+FROM opensuse/leap:15.0
+MAINTAINER SUSE Containers Team <containers@suse.com>
 
+# Install the entrypoint of this image.
+COPY init /
+
+# Install Portus and prepare the /certificates directory.
+RUN chmod +x /init && \
+    # Fetch the key from the obs://Virtualization:containers:Portus
+    # project. Sometimes the key server times out or has some other problem. In
+    # that case, we fall back to alternative key servers.
+    TMPDIR=/tmp/build && \
+    mkdir -m 0600 $TMPDIR && \
+    GPG_KEY=55a0b34d49501bb7ca474f5aa193fbb572174fc2 && \
+    found=''; \
+    for server in \
+      hkp://keys.gnupg.net:80 \
+      ha.pool.sks-keyservers.net \
+      hkp://keyserver.ubuntu.com:80 \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      pgp.mit.edu \
+    ; do \
+      echo "Fetching GPG key $GPG_KEY from $server"; \
+      gpg --homedir $TMPDIR --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEY" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEY" && exit 1; \
+    gpg --homedir $TMPDIR --export --armor $GPG_KEY > $TMPDIR/repo.key && \
+    rpm --import $TMPDIR/repo.key && \
+    rm -rf $TMPDIR && \
+    # Now add the repository and install portus.
+    zypper ar -f obs://Virtualization:containers:Portus:2.4/openSUSE_Leap_15.0 portus && \
+    zypper ref && \
+    zypper -n in --from portus ruby-common portus && \
+    zypper clean -a && \
+    # Prepare the certificates directory.
+    rm -rf /etc/pki/trust/anchors && \
+    ln -sf /certificates /etc/pki/trust/anchors
+
+EXPOSE 3000
+ENTRYPOINT ["/init"]
diff --git a/data/r/riot/riotbuild/Dockerfile b/data/r/riot/riotbuild/Dockerfile
--- a/data/r/riot/riotbuild/Dockerfile
+++ b/data/r/riot/riotbuild/Dockerfile
@@ -1,159 +1,256 @@
-#  
-# RIOT Dockerfile  
-#  
-# the resulting image will contain everything needed to build RIOT for all  
-# supported platforms. This is the largest build image, it takes about 1.5 GB
-in  
-# total.  
-#  
-# Setup: (only needed once per Dockerfile change)  
-# 1. install docker, add yourself to docker group, enable docker, relogin  
-# 2. # docker build -t riotbuild .  
-#  
-# Usage:  
-# 3. cd to riot root  
-# 4. # docker run -i -t -u $UID -v $(pwd):/data/riotbuild riotbuild
-./dist/tools/compile_test/compile_test.py  
-FROM ubuntu:xenial  
-  
-MAINTAINER Joakim Nohlgård <joakim.nohlgard@eistec.se>  
-  
-ENV DEBIAN_FRONTEND noninteractive  
-  
-# The following package groups will be installed:  
-# - upgrade all system packages to latest available version  
-# - native platform development and build system functionality (about 400 MB
-installed)  
-# - Cortex-M development (about 550 MB installed), through the gcc-arm-
-embedded PPA  
-# - MSP430 development (about 120 MB installed)  
-# - AVR development (about 110 MB installed)  
-# - LLVM/Clang build environment (about 125 MB installed)  
-# - x86 bare metal emulation (about 125 MB installed) (this pulls in all of
-X11)  
-# All apt files will be deleted afterwards to reduce the size of the container
-image.  
-# This is all done in a single RUN command to reduce the number of layers and
-to  
-# allow the cleanup to actually save space.  
-# Total size without cleaning is approximately 1.525 GB (2016-03-08)  
-# After adding the cleanup commands the size is approximately 1.497 GB  
-RUN \  
-dpkg --add-architecture i386 >&2 && \  
-echo 'Adding gcc-arm-embedded PPA' >&2 && \  
-echo "deb http://ppa.launchpad.net/team-gcc-arm-embedded/ppa/ubuntu xenial
-main" \  
-> /etc/apt/sources.list.d/gcc-arm-embedded.list && \  
-apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \  
-\--recv-keys B4D03348F75E3362B1E1C2A1D1FAA6ECF64D33B0 && \  
-echo 'Upgrading all system packages to the latest available versions' >&2 && \  
-apt-get update && apt-get -y dist-upgrade \  
-&& echo 'Installing native toolchain and build system functionality' >&2 && \  
-apt-get -y install \  
-bsdmainutils \  
-build-essential \  
-ccache \  
-coccinelle \  
-curl \  
-cppcheck \  
-doxygen \  
-gcc-multilib \  
-gdb \  
-g++-multilib \  
-git \  
-graphviz \  
-libpcre3 \  
-parallel \  
-pcregrep \  
-python \  
-python3 \  
-python3-pexpect \  
-python3-crypto \  
-python3-pyasn1 \  
-python3-ecdsa \  
-python3-flake8 \  
-p7zip \  
-subversion \  
-unzip \  
-vim-common \  
-wget \  
-&& echo 'Installing Cortex-M toolchain' >&2 && \  
-apt-get -y install \  
-gcc-arm-embedded \  
-&& echo 'Installing MSP430 toolchain' >&2 && \  
-apt-get -y install \  
-gcc-msp430 \  
-&& echo 'Installing AVR toolchain' >&2 && \  
-apt-get -y install \  
-gcc-avr \  
-binutils-avr \  
-avr-libc \  
-&& echo 'Installing LLVM/Clang toolchain' >&2 && \  
-apt-get -y install \  
-llvm \  
-clang \  
-&& echo 'Installing x86 bare metal emulation' >&2 && \  
-apt-get -y install \  
-qemu-system-x86 \  
-&& echo 'Installing socketCAN' >&2 && \  
-apt-get -y install \  
-libsocketcan-dev:i386 \  
-libsocketcan2:i386 \  
-&& echo 'Cleaning up installation files' >&2 && \  
-apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*  
-  
-# Install CMake 3.10  
-RUN wget -q https://cmake.org/files/v3.10/cmake-3.10.0.tar.gz -O- \  
-| tar -C /tmp -xz && cd /tmp/cmake-3.10.0/ && ./bootstrap && \  
-make && make install && cd && rm -rf /tmp/cmake-3.10.0  
-  
-# Install MIPS binary toolchain  
-RUN mkdir -p /opt && \  
-wget -q http://codescape-mips-
-sdk.imgtec.com/components/toolchain/2016.05-03/Codescape.GNU.Tools.Package.2016.05-03.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz
--O- \  
-| tar -C /opt -xz  
-  
-ENV PATH $PATH:/opt/mips-mti-elf/2016.05-03/bin  
-ENV MIPS_ELF_ROOT /opt/mips-mti-elf/2016.05-03  
-# Install RISC-V binary toolchain  
-RUN mkdir -p /opt && \  
-wget -q https://github.com/gnu-mcu-eclipse/riscv-none-
-gcc/releases/download/v7.2.0-2-20180110/gnu-mcu-eclipse-riscv-none-
-gcc-7.2.0-2-20180111-2230-centos64.tgz -O- \  
-| tar -C /opt -xz  
-  
-# HACK download arch linux' flex dynamic library  
-RUN wget -q
-https://sgp.mirror.pkgbuild.com/core/os/x86_64/flex-2.6.4-1-x86_64.pkg.tar.xz
--O- \  
-| tar -C / -xJ usr/lib/libfl.so.2.0.0  
-RUN ldconfig  
-  
-ENV PATH $PATH:/opt/gnu-mcu-eclipse/riscv-none-gcc/7.2.0-2-20180111-2230/bin  
-  
-# compile suid create_user binary  
-COPY create_user.c /tmp/create_user.c  
-RUN gcc -DHOMEDIR=\"/data/riotbuild\" -DUSERNAME=\"riotbuild\"
-/tmp/create_user.c -o /usr/local/bin/create_user \  
-&& chown root:root /usr/local/bin/create_user \  
-&& chmod u=rws,g=x,o=- /usr/local/bin/create_user \  
-&& rm /tmp/create_user.c  
-  
-# Create working directory for mounting the RIOT sources  
-RUN mkdir -m 777 -p /data/riotbuild  
-  
-# Set a global system-wide git user and email address  
-RUN git config --system user.name "riot" && \  
-git config --system user.email "riot@example.com"  
-  
-# Copy our entry point script (signal wrapper)  
-COPY run.sh /run.sh  
-ENTRYPOINT ["/bin/bash", "/run.sh"]  
-  
-# By default, run a shell when no command is specified on the docker command
-line  
-CMD ["/bin/bash"]  
-  
-WORKDIR /data/riotbuild  
+#
+# RIOT Dockerfile
+#
+# The resulting image will contain everything needed to build RIOT for all
+# supported platforms. This is the largest build image, it takes about 1.5 GB in
+# total.
+#
+# Setup:
+# 1. Install docker, add yourself to docker group, enable docker, relogin
+#
+# Use prebuilt image:
+# 1. Prebuilt image can be pulled from Docker Hub registry with:
+#      # docker pull riot/riotbuild
+# 
+# Use own build image:
+# 1. Build own image based on latest base OS image:
+#      # docker build --pull -t riotbuild .
+#
+# Usage:
+# 1. cd to riot root
+# 2. # docker run -i -t -u $UID -v $(pwd):/data/riotbuild riotbuild ./dist/tools/compile_test/compile_test.py
 
+FROM ubuntu:bionic
+
+LABEL maintainer="Kaspar Schleiser <kaspar@riot-os.org>"
+
+ENV DEBIAN_FRONTEND noninteractive
+
+ENV LC_ALL C.UTF-8
+ENV LANG C.UTF-8
+
+# The following package groups will be installed:
+# - update the package index files to latest available version
+# - native platform development and build system functionality (about 400 MB installed)
+# - Cortex-M development (about 550 MB installed), through the gcc-arm-embedded PPA
+# - MSP430 development (about 120 MB installed)
+# - AVR development (about 110 MB installed)
+# - LLVM/Clang build environment (about 125 MB installed)
+# All apt files will be deleted afterwards to reduce the size of the container image.
+# The OS must not be updated by apt. Docker image should be build against the latest
+#  updated base OS image. This can be forced with `--pull` flag.
+# This is all done in a single RUN command to reduce the number of layers and to
+# allow the cleanup to actually save space.
+# Total size without cleaning is approximately 1.525 GB (2016-03-08)
+# After adding the cleanup commands the size is approximately 1.497 GB
+RUN \
+    dpkg --add-architecture i386 >&2 && \
+    echo 'Update the package index files to latest available versions' >&2 && \
+    apt-get update \
+    && echo 'Installing native toolchain and build system functionality' >&2 && \
+    apt-get -y --no-install-recommends install \
+        automake \
+        bsdmainutils \
+        build-essential \
+        ca-certificates \
+        ccache \
+        cmake \
+        coccinelle \
+        curl \
+        cppcheck \
+        doxygen \
+        gcc-multilib \
+        gdb \
+        g++-multilib \
+        git \
+        graphviz \
+        less \
+        libffi-dev \
+        libpcre3 \
+        libtool \
+        m4 \
+        parallel \
+        pcregrep \
+        protobuf-compiler \
+        python \
+        python3 \
+        python3-dev \
+        python3-pip \
+        python3-setuptools \
+        python3-wheel \
+        p7zip \
+        rsync \
+        ssh-client \
+        subversion \
+        unzip \
+        vera++ \
+        vim-common \
+        wget \
+        xsltproc \
+    && echo 'Installing MSP430 toolchain' >&2 && \
+    apt-get -y --no-install-recommends install \
+        gcc-msp430 \
+        msp430-libc \
+    && echo 'Installing AVR toolchain' >&2 && \
+    apt-get -y --no-install-recommends install \
+        gcc-avr \
+        binutils-avr \
+        avr-libc \
+    && echo 'Installing LLVM/Clang toolchain' >&2 && \
+    apt-get -y --no-install-recommends install \
+        llvm \
+        clang \
+        clang-tools \
+    && echo 'Installing socketCAN' >&2 && \
+    apt-get -y --no-install-recommends install \
+        libsocketcan-dev:i386 \
+        libsocketcan2:i386 \
+    && echo 'Cleaning up installation files' >&2 && \
+    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+# Install ARM GNU embedded toolchain
+# For updates, see https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
+RUN echo 'Installing arm-none-eabi toolchain from arm.com' >&2 && \
+    mkdir -p /opt && \
+    curl -L -o /opt/gcc-arm-none-eabi.tar.bz2 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update' && \
+    echo '299ebd3f1c2c90930d28ab82e5d8d6c0 */opt/gcc-arm-none-eabi.tar.bz2' | md5sum -c && \
+    tar -C /opt -jxf /opt/gcc-arm-none-eabi.tar.bz2 && \
+    rm -f /opt/gcc-arm-none-eabi.tar.bz2 && \
+    echo 'Removing documentation' >&2 && \
+    rm -rf /opt/gcc-arm-none-eabi-*/share/doc
+    # No need to dedup, the ARM toolchain is already using hard links for the duplicated files
+
+ENV PATH ${PATH}:/opt/gcc-arm-none-eabi-7-2018-q2-update/bin
+
+# Install MIPS binary toolchain
+# For updates: https://www.mips.com/develop/tools/codescape-mips-sdk/ (select "Codescape GNU Toolchain")
+ARG MIPS_VERSION=2018.09-03
+RUN echo 'Installing mips-mti-elf toolchain from mips.com' >&2 && \
+    mkdir -p /opt && \
+    curl -L "https://codescape.mips.com/components/toolchain/${MIPS_VERSION}/Codescape.GNU.Tools.Package.${MIPS_VERSION}.for.MIPS.MTI.Bare.Metal.CentOS-6.x86_64.tar.gz" -o - \
+        | tar -C /opt -zx && \
+    echo 'Removing documentation and translations' >&2 && \
+    rm -rf /opt/mips-mti-elf/*/share/{doc,info,man,locale} && \
+    echo 'Deduplicating binaries' && \
+    cd /opt/mips-mti-elf/*/mips-mti-elf/bin && \
+    for f in *; do test -f "../../bin/mips-mti-elf-$f" && ln -f "../../bin/mips-mti-elf-$f" "$f"; done && cd -
+
+ENV MIPS_ELF_ROOT /opt/mips-mti-elf/${MIPS_VERSION}
+
+ENV PATH ${PATH}:${MIPS_ELF_ROOT}/bin
+
+# Install RISC-V binary toolchain
+ARG RISCV_VERSION=8.2.0-2.2-20190521
+ARG RISCV_BUILD=0004
+RUN mkdir -p /opt && \
+        wget -q https://github.com/gnu-mcu-eclipse/riscv-none-gcc/releases/download/v${RISCV_VERSION}/gnu-mcu-eclipse-riscv-none-gcc-${RISCV_VERSION}-${RISCV_BUILD}-centos64.tgz -O- \
+        | tar -C /opt -xz && \
+    echo 'Removing documentation' >&2 && \
+      rm -rf /opt/gnu-mcu-eclipse/riscv-none-gcc/*/share/doc && \
+    echo 'Deduplicating binaries' >&2 && \
+    cd /opt/gnu-mcu-eclipse/riscv-none-gcc/*/riscv-none-embed/bin && \
+      for f in *; do test -f "../../bin/riscv-none-embed-$f" && \
+       ln -f "../../bin/riscv-none-embed-$f" "$f"; \
+      done && \
+    cd -
+
+ENV PATH $PATH:/opt/gnu-mcu-eclipse/riscv-none-gcc/${RISCV_VERSION}-${RISCV_BUILD}/bin
+
+# compile suid create_user binary
+COPY create_user.c /tmp/create_user.c
+RUN gcc -DHOMEDIR=\"/data/riotbuild\" -DUSERNAME=\"riotbuild\" /tmp/create_user.c -o /usr/local/bin/create_user \
+    && chown root:root /usr/local/bin/create_user \
+    && chmod u=rws,g=x,o=- /usr/local/bin/create_user \
+    && rm /tmp/create_user.c
+
+# Install complete ESP8266 toolchain in /opt/esp (146 MB after cleanup)
+RUN echo 'Installing ESP8266 toolchain' >&2 && \
+    cd /opt && \
+    git clone https://github.com/gschorcht/RIOT-Xtensa-ESP8266-toolchain.git esp && \
+    cd esp && \
+    git checkout -q df38b06 && \
+    rm -rf .git
+
+ENV PATH $PATH:/opt/esp/esp-open-sdk/xtensa-lx106-elf/bin
+ENV ESP8266_SDK_DIR /opt/esp/esp-open-sdk/sdk
+ENV ESP8266_NEWLIB_DIR /opt/esp/newlib-xtensa
+
+# Install complete ESP8266 toolchain in /opt/esp (139 MB after cleanup)
+# remember https://github.com/RIOT-OS/RIOT/pull/10801 when updating
+# NOTE: We install the toolchain for the RTOS SDK in parallel in the first
+# step and remove the old version as soon as the RIOT port for the ESP8266
+# RTOS SDK has been merged.
+RUN echo 'Installing ESP8266 toolchain' >&2 && \
+    mkdir -p /opt/esp && \
+    cd /opt/esp && \
+    git clone https://github.com/gschorcht/xtensa-esp8266-elf && \
+    cd xtensa-esp8266-elf && \
+    git checkout -q 696257c2b43e2a107d3108b2c1ca6d5df3fb1a6f && \
+    rm -rf .git && \
+    cd /opt/esp && \
+    git clone https://github.com/gschorcht/RIOT-Xtensa-ESP8266-RTOS-SDK.git ESP8266_RTOS_SDK && \
+    cd ESP8266_RTOS_SDK/ && \
+    git checkout -q c0174eff7278eb5beea66ce1f65b7af57432d2a9 && \
+    rm -rf .git* docs examples make tools && \
+    cd components && \
+    rm -rf app_update aws_iot bootloader cjson coap espos esp-tls freertos \
+           jsmn libsodium log mdns mqtt newlib partition_table pthread \
+           smartconfig_ack spiffs ssl tcpip_adapter vfs && \
+    find . -name '*.[csS]' -exec rm {} \;
+
+ENV PATH $PATH:/opt/esp/xtensa-esp8266-elf/bin
+ENV ESP8266_RTOS_SDK_DIR /opt/esp/ESP8266_RTOS_SDK
+
+# Install ESP32 toolchain in /opt/esp (181 MB after cleanup)
+# remember https://github.com/RIOT-OS/RIOT/pull/10801 when updating
+RUN echo 'Installing ESP32 toolchain' >&2 && \
+    mkdir -p /opt/esp && \
+    cd /opt/esp && \
+    git clone https://github.com/espressif/esp-idf.git && \
+    cd esp-idf && \
+    git checkout -q f198339ec09e90666150672884535802304d23ec && \
+    git submodule update --init --recursive && \
+    rm -rf .git* docs examples make tools && \
+    rm -f add_path.sh CONTRIBUTING.rst Kconfig Kconfig.compiler && \
+    cd components && \
+    rm -rf app_trace app_update aws_iot bootloader bt coap console cxx \
+           esp_adc_cal espcoredump esp_http_client esp-tls expat fatfs \
+           freertos idf_test jsmn json libsodium log lwip mbedtls mdns \
+           micro-ecc nghttp openssl partition_table pthread sdmmc spiffs \
+           tcpip_adapter ulp vfs wear_levelling xtensa-debug-module && \
+    find . -name '*.[csS]' -exec rm {} \; && \
+    cd /opt/esp && \
+    git clone https://github.com/gschorcht/xtensa-esp32-elf.git && \
+    cd xtensa-esp32-elf && \
+    git checkout -q ca40fb4c219accf8e7c8eab68f58a7fc14cadbab
+
+ENV PATH $PATH:/opt/esp/xtensa-esp32-elf/bin
+
+ARG MSP430_URL=https://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports
+ARG MSP430_VERSION=8.3.0.16_linux64
+RUN echo 'Installing TI MSP430 ELF toolchain' >&2 && \
+        wget -q ${MSP430_URL}/msp430-gcc-${MSP430_VERSION}.tar.bz2 -O- \
+            | tar -C /opt -xj
+ENV PATH $PATH:/opt/msp430-gcc-${MSP430_VERSION}/bin
+
+# install required python packages from file
+COPY requirements.txt /tmp/requirements.txt
+RUN echo 'Installing python3 packages' >&2 \
+    && pip3 install --no-cache-dir -r /tmp/requirements.txt \
+    && rm /tmp/requirements.txt
+
+# Create working directory for mounting the RIOT sources
+RUN mkdir -m 777 -p /data/riotbuild
+
+# Set a global system-wide git user and email address
+RUN git config --system user.name "riot" && \
+    git config --system user.email "riot@example.com"
+
+# Copy our entry point script (signal wrapper)
+COPY run.sh /run.sh
+ENTRYPOINT ["/bin/bash", "/run.sh"]
+
+# By default, run a shell when no command is specified on the docker command line
+CMD ["/bin/bash"]
+
+WORKDIR /data/riotbuild
diff --git a/data/w/way2web/pipeline-apps/Dockerfile b/data/w/way2web/pipeline-apps/Dockerfile
--- a/data/w/way2web/pipeline-apps/Dockerfile
+++ b/data/w/way2web/pipeline-apps/Dockerfile
@@ -1,97 +1,120 @@
-FROM php:7.1-cli  
-  
-MAINTAINER Way2Web <developers@way2web.nl>  
-  
-RUN DEBIAN_FRONTEND=noninteractive  
-  
-ARG TZ=Europe/Amsterdam  
-ENV TZ ${TZ}  
-  
-# add the mysql key  
-RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 5072E1F5  
-  
-# Prepare and install mysql  
-RUN echo "mysql-community-server mysql-community-server/root-pass password
-root" | debconf-set-selections &&\  
-echo "mysql-community-server mysql-community-server/re-root-pass password
-root" | debconf-set-selections &&\  
-echo "mysql-apt-config mysql-apt-config/enable-repo select mysql-5.6" |
-debconf-set-selections &&\  
-curl -sSL http://repo.mysql.com/mysql-apt-config_0.2.1-1debian7_all.deb -o
-./mysql-apt-config_0.2.1-1debian7_all.deb &&\  
-dpkg -i mysql-apt-config_0.2.1-1debian7_all.deb  
-  
-# Install dependencies  
-RUN apt-get update && apt-get install --no-install-recommends -y \  
-mysql-community-server \  
-libfreetype6-dev \  
-libjpeg62-turbo-dev \  
-libmcrypt-dev \  
-libpng12-dev \  
-libcurl4-nss-dev \  
-libc-client-dev \  
-libkrb5-dev \  
-firebird2.5-dev \  
-libicu-dev \  
-libxml2-dev \  
-libxslt1-dev \  
-libbz2-dev \  
-ssmtp \  
-git \  
-mercurial \  
-zip \  
-xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-
-base xfonts-scalable imagemagick x11-apps  
-  
-# Install PHP extensions  
-RUN docker-php-ext-install -j$(nproc) bz2 &&\  
-docker-php-ext-install -j$(nproc) mcrypt &&\  
-docker-php-ext-install -j$(nproc) curl &&\  
-docker-php-ext-install -j$(nproc) mbstring &&\  
-docker-php-ext-install -j$(nproc) iconv &&\  
-docker-php-ext-install -j$(nproc) interbase &&\  
-docker-php-ext-install -j$(nproc) intl &&\  
-docker-php-ext-install -j$(nproc) soap &&\  
-docker-php-ext-install -j$(nproc) xmlrpc &&\  
-docker-php-ext-install -j$(nproc) xsl &&\  
-docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-
-dir=/usr/include/ &&\  
-docker-php-ext-install -j$(nproc) gd &&\  
-docker-php-ext-configure imap --with-kerberos --with-imap-ssl &&\  
-docker-php-ext-install imap &&\  
-docker-php-ext-install mysqli pdo pdo_mysql &&\  
-docker-php-ext-install zip  
-  
-RUN docker-php-ext-configure pcntl --enable-pcntl && \  
-docker-php-ext-install pcntl  
-  
-# Install Composer for Laravel/Codeigniter, NodeJS and other dependencies  
-RUN curl -sSL https://deb.nodesource.com/setup_6.x | bash - &&\  
-apt-get -y --no-install-recommends install nodejs &&\  
-curl -sSL https://getcomposer.org/installer | php -- --filename=composer
---install-dir=/usr/bin &&\  
-curl -sSL https://phar.phpunit.de/phpunit.phar -o /usr/bin/phpunit && chmod +x
-/usr/bin/phpunit &&\  
-curl -sSL http://codeception.com/codecept.phar -o /usr/bin/codecept && chmod
-+x /usr/bin/codecept &&\  
-curl -sSL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o
-/usr/bin/phpcs && chmod +x /usr/bin/phpcs &&\  
-curl -sSL http://static.phpmd.org/php/latest/phpmd.phar -o /usr/bin/phpmd &&
-chmod +x /usr/bin/phpmd &&\  
-curl -sSL https://phar.phpunit.de/phpcpd.phar -o /usr/bin/phpcpd && chmod +x
-/usr/bin/phpcpd &&\  
-curl -o- -L https://yarnpkg.com/install.sh | bash  
-  
-#Install chrome - needed for Laravel Dusk  
-RUN curl -sS https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
-add - && \  
-sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
-main" >> /etc/apt/sources.list.d/google-chrome.list' && \  
-apt-get update && apt-get install -y google-chrome-stable  
-  
-# Clean up APT when done  
-RUN apt-get autoclean &&\  
-apt-get clean &&\  
-apt-get autoremove &&\  
-rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*  
+FROM php:7.2-cli
 
+MAINTAINER Way2Web <developers@way2web.nl>
+
+RUN DEBIAN_FRONTEND=noninteractive
+
+ARG TZ=Europe/Amsterdam
+ENV TZ ${TZ}
+
+RUN apt-get update && apt-get install -y gnupg apt-transport-https ca-certificates lsb-release wget
+
+RUN set -ex \
+  && for key in \
+    5072E1F5 \
+  ; do \
+    gpg --batch --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
+    gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" || \
+    gpg --batch --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key" ; \
+  done; exit 0
+
+# Prepare and install mysql
+RUN echo "mysql-community-server mysql-community-server/root-pass password root" | debconf-set-selections &&\
+    echo "mysql-community-server mysql-community-server/re-root-pass password root" | debconf-set-selections &&\
+    echo "mysql-apt-config mysql-apt-config/select-server select mysql-5.7" | debconf-set-selections &&\
+    curl -sSL http://repo.mysql.com/mysql-apt-config_0.8.9-1_all.deb -o ./mysql-apt-config_0.8.9-1_all.deb &&\
+    export DEBIAN_FRONTEND=noninteractive &&\
+    dpkg -i mysql-apt-config_0.8.9-1_all.deb
+
+# Install dependencies
+RUN apt-get update && apt-get install --no-install-recommends -y --force-yes \
+    mysql-community-server \
+    mysql-client \
+    libfreetype6-dev \
+    libjpeg62-turbo-dev \
+    libmcrypt-dev \
+    libpng-dev \
+    libcurl4-nss-dev \
+    libc-client-dev \
+    libkrb5-dev \
+    firebird-dev \
+    libicu-dev \
+    libxml2-dev \
+    libxslt1-dev \
+    libbz2-dev \
+    libzip-dev \
+    ssmtp \
+    git \
+    mercurial \
+    zip \
+    xvfb \
+    gtk2-engines-pixbuf \
+    xfonts-cyrillic \
+    xfonts-100dpi \
+    xfonts-75dpi  \
+    xfonts-base \
+    xfonts-scalable \
+    imagemagick \
+    x11-apps
+
+# Add maximum backwards compatibility with MySQL 5.6
+RUN echo "[mysqld]" >> /etc/mysql/conf.d/z-pipelines-config.cnf && \
+    echo 'sql_mode = "NO_ENGINE_SUBSTITUTION"' >> /etc/mysql/conf.d/z-pipelines-config.cnf
+
+# Install PHP extensions
+RUN docker-php-ext-install -j$(nproc) bz2 &&\
+    docker-php-ext-install -j$(nproc) bcmath &&\
+    docker-php-ext-install -j$(nproc) curl &&\
+    docker-php-ext-install -j$(nproc) mbstring &&\
+    docker-php-ext-install -j$(nproc) iconv &&\
+    docker-php-ext-install -j$(nproc) interbase &&\
+    docker-php-ext-install -j$(nproc) intl &&\
+    docker-php-ext-install -j$(nproc) soap &&\
+    docker-php-ext-install -j$(nproc) xmlrpc &&\
+    docker-php-ext-install -j$(nproc) xsl &&\
+    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ &&\
+    docker-php-ext-install -j$(nproc) gd &&\
+    docker-php-ext-configure imap --with-kerberos --with-imap-ssl &&\
+    docker-php-ext-install imap &&\
+    docker-php-ext-install mysqli pdo pdo_mysql &&\
+    docker-php-ext-install zip
+    
+RUN docker-php-ext-configure pcntl --enable-pcntl && \
+  docker-php-ext-install pcntl
+
+# Prepare and install NVM
+ENV NVM_DIR /root/.nvm
+
+RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash &&\
+  . /root/.nvm/nvm.sh &&\
+  nvm install 10 &&\
+  nvm install 8 &&\
+  nvm install 6 &&\
+  nvm alias default 10
+  
+RUN echo "" >> ~/.bashrc && \
+  echo 'export NVM_DIR="/root/.nvm"' >> ~/.bashrc && \
+  echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.bashrc \
+  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
+  curl -o- -L https://yarnpkg.com/install.sh | bash; \
+  echo "" >> ~/.bashrc && \
+  echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> ~/.bashrc
+
+# Install Composer for Laravel/Codeigniter and other dependencies
+RUN curl -sSL https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/bin &&\
+    curl -sSL https://phar.phpunit.de/phpunit.phar -o /usr/bin/phpunit  && chmod +x /usr/bin/phpunit &&\
+    curl -sSL http://codeception.com/codecept.phar -o /usr/bin/codecept && chmod +x /usr/bin/codecept &&\
+    curl -sSL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o /usr/bin/phpcs && chmod +x /usr/bin/phpcs &&\
+    curl -sSL http://static.phpmd.org/php/latest/phpmd.phar -o /usr/bin/phpmd && chmod +x /usr/bin/phpmd &&\
+    curl -sSL https://phar.phpunit.de/phpcpd.phar -o /usr/bin/phpcpd && chmod +x /usr/bin/phpcpd
+
+#Install chrome - needed for Laravel Dusk
+RUN curl -sS https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
+    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
+    apt-get update && apt-get install -y google-chrome-stable
+
+# Clean up APT when done
+RUN apt-get autoclean &&\
+    apt-get clean &&\
+    apt-get autoremove &&\
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
